### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by 123ufo** [novoda/bintray-release#103]
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ouchadam** [comment]
Hi @	123ufo what version of the library are you using? 

If possible could you try `0.4.0` with `gradle 3.2.1`?

**Comment by 123ufo** [comment]
@ouchadam libray 0.04 and gradle 2.2.0

**Comment by ouchadam** [comment]
without a stacktrace there's no much we can do for this. If you're still having a an issue please reopen with a full log 😄  thanks!
