### ISSUE TITLE
Support override

### ISSUE THREAD

**Issue by Ghedeon** [novoda/bintray-release#104]
Hi,

Awesome plugin, do you plan to support `override` param from bintray API? Like `gradle-bintray-plugin` does, for example.

Thank you.

**Comment by StefMa** [comment]
Hey @ghedeon
Sry for the late response.

What do you mean exactly with the override param? I am not familiar with the `gradle-bintray-pluign`. Can you share some details what do you mean?

**Comment by StefMa** [comment]
OK. Just checked the plugin Readme page and found the override configuration.
See https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md#plugin-dsl

We think about it will possibly create a PR for that 👍
