### ISSUE TITLE
Available from Gradle plugins' repository

### ISSUE THREAD

**Issue by kamikat** [novoda/bintray-release#106]
Gradle 2.1 introduced a plugin mechanism and add the plugin to <https://plugins.gradle.org/> which makes it easier to use the plugin.

Before Gradle 2.1:

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.novoda:bintray-release:<latest-version>'
    }
}

apply plugin: 'com.novoda.bintray-release'
```

After:

```groovy
plugins {
  id 'com.novoda:bintray-release:<latest-version>'
}
```

**Comment by wkp111** [comment]
After Gradle 2.1, It can not use

**Comment by StefMa** [comment]
@wpk111 it is not usable with the new plugin mechanism as bintray-release isn't published to plugins.gradle.org.

I don't know if it's worth to create a account and publish it there as well?!
Most of gradle users use the "old" mechanism and are very familiar with it. Also because not all used plugins are available there.

**Comment by StefMa** [comment]
@Mecharyry what do you say about that?
Should we support it?

**Comment by StefMa** [comment]
This plugin is not available in the gradlePluginPortal() and would not be published there.
As a "workaround" you can use this:
settings.gradle
```gradle
pluginManagement {
    repositories {
        // Either use this or gradlePluginPortal()
        // Depends on the used gradle version
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.novoda.bintray-release") {
                useModule("com.novoda:bintray-release:${requested.version}")
            }
        }
    }
}
```

build.gradle
```gradle
plugins {
    id 'com.novoda.bintray-release' version "0.8.0"
}
```

**Comment by tasomaniac** [comment]
@StefMa should repositories have `jcenter()` in above code.

**Comment by StefMa** [comment]
It could, yes.
But since the plugin portal redirect to jcenter this configuration is
possible as well...
