### ISSUE TITLE
`bintrayUpload` task fails on Java 1.7

### ISSUE THREAD

**Issue by kamikat** [novoda/bintray-release#107]
Here's a known bug of [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin/issues/131) version 1.7.2 which is used in 0.4.0 release. Downgrade this plugin to 0.3.5 fixes this problem.

**Comment by ouchadam** [comment]
seems that [1.7.3](https://github.com/bintray/gradle-bintray-plugin) fixes this, will test upgrading, thanks for raising 👍

**Comment by blundell** [comment]
It is fixed
