### ISSUE TITLE
Repository name hardcoded to 'maven'

### ISSUE THREAD

**Issue by bkolarov-appolica** [novoda/bintray-release#109]
We have an account in bintray with a repository with different name. We are unable to publish our library with this helper plugin, because of the hardcoded 'maven' repo name. Do you have any intentions to change that? 
Thank you :)

**Comment by mr-archano** [comment]
We'll look into that, thanks for the heads-up @bkolarov-appolica. Watch this space for an update 👍

**Comment by ouchadam** [comment]
@bkolarov-appolica the `publish` closure provides a `repoName` field which you can set to override the default 'maven'

**Comment by andrewlord1990** [comment]
This is described in the wiki: https://github.com/novoda/bintray-release/wiki/Configuration-of-the-publish-closure

So I think this issue can be closed 😄

**Comment by ouchadam** [comment]
agreed!
