### ISSUE TITLE
Support for Gradle 3.4

### ISSUE THREAD

**Issue by afollestad** [novoda/bintray-release#113]
This error occurs specifically when this library is a dependency in my Gradle file, while using version 3.4 of Gradle:

<img width="1189" alt="screen shot 2017-03-08 at 1 18 32 pm" src="https://cloud.githubusercontent.com/assets/1820165/23719639/cadca146-0401-11e7-93fa-0ac5b81728e2.png">

**Comment by mr-archano** [comment]
Already covered by #112, we're discussing a possible solution with the Gradle team.
