### ISSUE TITLE
Skipping upload for missing file 

### ISSUE THREAD

**Issue by yilylong** [novoda/bintray-release#114]
Skipping upload for missing file 'E:\MyAndroidSudioProgects\ChannleManagerView\channeltagviewLib\build\libs\channeltagviewLib-sources.jar'.
Skipping upload for missing file 'E:\MyAndroidSudioProgects\ChannleManagerView\channeltagviewLib\build\libs\channeltagviewLib-javadoc.jar'.
Skipping upload for missing file 'E:\MyAndroidSudioProgects\ChannleManagerView\channeltagviewLib\build\publications\release\pom-default.xml'

**Comment by ouchadam** [comment]
Hi @yilylong 😄  do those files exist in your workspace?

**Comment by mr-archano** [comment]
Hi @yilylong it would be great to get more info about your project setup. We would prefer a small project that highlights the problem at hand. The issue as it is now unfortunately is not actionable, so I'm closing it. Feel free to open a new issue giving us enough context to give you some help.
