### ISSUE TITLE
Plugin with id 'com.novoda.bintray-release' not found

### ISSUE THREAD

**Issue by vijaydave117** [novoda/bintray-release#119]
Plugin with id 'com.novoda.bintray-release' not found issue... kindly reply ASAP...
i want to develop RichTextEditor demo for insert data in database and also select data from database in exact form which i was insert...
Kindly help me out
Thnks

**Comment by StefMa** [comment]
Hey, 

can you show you setup code? 
Have you added `jcenter` as repository and `com.novoda:bintray-release:0.4.0` as classpath dependency?

**Comment by vijaydave117** [comment]
Yes u have tried but still not resolved. Can u help me out? if u can send me working code then its awesome

**Comment by StefMa** [comment]
How to setup is explained in the [`README`](https://github.com/novoda/bintray-release#adding-to-project) 😄
Anyway. You can take a look at [this project](https://github.com/grandcentrix/thirtyinch) how to use it.
[This](https://github.com/grandcentrix/ThirtyInch/blob/v0.8.0-rc4/thirtyinch/build.gradle) `build.gradle` module added the [`buildscript`](https://github.com/grandcentrix/ThirtyInch/blob/v0.8.0-rc4/thirtyinch/build.gradle#L1) section. It will be [applied direct](https://github.com/grandcentrix/ThirtyInch/blob/v0.8.0-rc4/thirtyinch/build.gradle#L11) after this section.

**Comment by vijaydave117** [comment]
Error:Could not get unknown property 'sourceSets' for root project 'RTEsample' of type org.gradle.api.Project.
Got this Error

**Comment by StefMa** [comment]
I can't help you if you don't help me.
> can you show your setup code?

**Comment by vijaydave117** [comment]
build.gradle (Project)
===========
// Top-level build file where you can add configuration options common to all sub-projects/modules.

apply plugin: 'bintray-release'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath "com.novoda:bintray-release:0.4.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
publish {
    userOrg = 'novoda'
    groupId = 'com.novoda'
    artifactId = 'bintray-release'
    publishVersion = '0.3.4'
    desc = 'Oh hi, this is a nice description for a project, right?'
    website = 'https://github.com/novoda/bintray-release'
}
--------------------------------------------------------------
build.gradle (Module)
=============================
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.nexcod.rtesample"
        minSdkVersion 24
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'
    compile project(':richeditor')
}

**Comment by StefMa** [comment]
Please take a look at the Readme. There it saß you have to add the
configuration to your module build.gradle. Not to your root build.gradle.
You can also take a look to the library I've send you above..

**Comment by vijaydave117** [comment]
Thanks  a lot... its working.... very silly mistake i have done.

can u help to implement all functionality like bold, italic and insert image and all?

**Comment by StefMa** [comment]
This is not a support forum for implementation of your app. Use
stackoverflow or something.
If it working now, please close the issue. Thank you

**Comment by vijaydave117** [comment]
Thanks for your support

**Comment by xrigau** [comment]
thanks @StefMa for helping with this 💯 🎉 🏅

**Comment by iandreyshev** [comment]
@StefMa can you help me with sourceSet problem ? I try to publish my code with bintray-release

**Comment by StefMa** [comment]
Hey @iandreyshev,
what sourceSet problem are you talking?
I'm maintain my own fork of the [`bintray-release`](https://github.com/StefMa/bintray-release). 
Feel free to use this plugin and open an issue there with more details about your problem.

**Comment by iandreyshev** [comment]
@StefMa Hi
I want to publish library to bintray for the first experience, but take that error:
`Could not get unknown property 'sourceSets' for root project 'Vext' of type org.gradle.api.Project.`
This lib published in my profile

I can try to do this with you fork

**Comment by mr-archano** [comment]
@iandreyshev you should open an issue with more details about your issue (that seems totally unrelated to the one captured here): a sample of your build script and some repro steps would help.

@StefMa I keep seeing you providing "you should use my own fork" as blanket reply for all the issues open and I find it of very poor taste. Please refrain from doing this, as this is not a constructive way of collaborating on an open source project.
If you are not interested to be a collaborator of this project we'll understand, and I can remove you as collaborator of this repo asap. If you want to talk about this feel free to reach me at the email in my GitHub profile.
