### ISSUE TITLE
bintrayUpload: Could not find publication: release.

### ISSUE THREAD

**Issue by HongJun2046** [novoda/bintray-release#122]
classpath 'com.novoda:bintray-release:0.5.0'
publish {

    userOrg = 'zmanchina'
    groupId = 'com.hongjun'
    artifactId = 'rxbaidulocation'
    publishVersion = '1.0.0-SNAPSHOT'
    bintrayUser = properties.getProperty("bintray.user")
    bintrayKey = properties.getProperty("bintray.apikey")
    desc = 'android library baidulocaction in rxjava'
    website = 'https://github.com/HongJun2046/RxBaiduLocation'
}

**Comment by StefMa** [comment]
You have to use at least gradle version 3.4 with bintray-release 0.5.0.
Check the error message you got or this PR
https://github.com/novoda/bintray-release/pull/116

Of you can't use a higher gradle version than 3.3 use bintray-release
0.4.0.

**Comment by passsy** [comment]
Do you have build flavours? Depending on that you have to change the name of the publication

**Comment by HongJun2046** [comment]
@StefMa thanks, i do it
