### ISSUE TITLE
ParserConfigurationSettings , method: <init> signature: ()V) Illegal type in constant pool

### ISSUE THREAD

**Issue by petma** [novoda/bintray-release#124]
Error:Execution failed for task ':pickerview:mergeReleaseShaders'.
> (class: org/apache/xerces/util/ParserConfigurationSettings, method: <init> signature: ()V) Illegal type in constant pool

**Comment by StefMa** [comment]
Some more information would be useful. How have you set up bintray-release?
Which other plugins are u using? Post your build.gradle...

**Comment by blundell** [comment]
cannot reproduce this problem. Please re-open if you have a reproducible demo
