### ISSUE TITLE
Can I use local.properties to store bintrayUser and bintrayKey?

### ISSUE THREAD

**Issue by CoXier** [novoda/bintray-release#125]
I think it's too broing to put many paramers every time I want to update my library version.So I store bintrayUser and bintrayKey into `local.properties`.

`local.properties`:

```gradle
ndk.dir=/home/coxier/Android/Sdk/ndk-bundle
sdk.dir=/home/coxier/Android/Sdk
bintrayUser=coxier
bintrayKey=xxxxx
```

However when I invoke:
```gradle
 ./gradlew clean build bintrayUpload -PdryRun=false
```
I get error:

> * What went wrong:
Execution failed for task ':library:bintrayUpload'.
> Bintray user cannot be empty!

----------------
bintray-release version :0.5.0
gradle version:3.4

**Comment by StefMa** [comment]
Normally that should work.
Don't know why it isn't working. Can you try to put your username and key
into " (so that is an string)? I guess it wouldn't fix it but try it 😊

Otherwise I will investigate in it...

**Comment by StefMa** [comment]
Ahh wait. You are talking about the local.properties. That is the wrong
file to store such informations. The best way to store such keys in a in
your gradle.properties inside your gradle home (~/.gradle/) see
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties

**Comment by CoXier** [comment]
However I don't think you are right because such as NDK settings is here.

I have found out solution.

```gradle
    Properties properties = new Properties()
    InputStream inputStream = project.rootProject.file('local.properties').newDataInputStream() ;
    properties.load( inputStream )
    bintrayUser = properties.getProperty('bintrayUser')
    bintrayKey = properties.getProperty('bintrayKey')
```

**Comment by StefMa** [comment]
Yep, right. The ndk (and sdk)  path is defined here. If you develop in a
team it may happen that each developer have  a different path for the
ndk/sdk location. So you don't have to add these file into your source
control system. Otherwise you will got in trouble.

**Comment by mr-archano** [comment]
@CoXier late to the party, but you could also use this plugin to streamline your setup: https://github.com/novoda/gradle-build-properties-plugin
> Keep your secrets secret. External properties files support for your build scripts.
