### ISSUE TITLE
Bintray-uplopad: Could not find publication: release.

### ISSUE THREAD

**Issue by NoGirlFriendException** [novoda/bintray-release#128]
Using bintry-release 0.5.0 in a com.android.library project with Gradle 3.5 , i see the following  
message : Could not find publication: release.
but i upload the lib to jcenter success... why?

**Comment by kkmike999** [comment]
may be you should see #96

**Comment by hrules6872** [comment]
Version 0.4.0 works correctly

**Comment by blundell** [comment]
Please use version `0.4.0` with your version of Gradle.

**Comment by eastman-sz** [comment]
> Using bintry-release 0.5.0 in a com.android.library project with Gradle 3.5 , i see the following
> message : Could not find publication: release.
> but i upload the lib to jcenter success... why?

:commonViews:bintrayUpload: Could not find publication: release.
I also upload successful. what's wrong?
