### ISSUE TITLE
how publish kotlin library

### ISSUE THREAD

**Issue by vihuela** [novoda/bintray-release#130]
this is library gradle file：https://github.com/vihuela/Kotlin-mvpro/blob/master/mvpro/build.gradle
 execute bintrayUpload  show console

```
 'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
 'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
 'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
 'kapt.generateStubs' is not used by the 'kotlin-kapt' plugin
 Publication release not found in project :mvpro.
 :mvpro:bintrayUpload
 :mvpro:bintrayUpload: Could not find publication: release.
```

**Comment by xrigau** [comment]
Hey @vihuela thanks for reporting this issue! Unfortunately we haven't had a chance to use this plugin for Kotlin projects, as soon as we do we'll add support for it, meanwhile feel free to issue a PR if you manage to fix the issue

**Comment by vihuela** [comment]
ok..get it，i will try haha

**Comment by StefMa** [comment]
@vihuela @xrigau 
I think it would be better to keep that issue open 👍

**Comment by xrigau** [comment]
yeah 👍

**Comment by vihuela** [comment]
@StefMa i solve it，no fix issue，and..chance Dependency order
①create android libray module
②compile bintray-release，ensure have under task 
![11](https://user-images.githubusercontent.com/6533060/27940844-dcdd5bc6-62ff-11e7-9de2-a6fc4878290d.png)
③and then compile kotlin etc...
④my question is that the order is wrong.wrong.wrong，bug bug bug..
