### ISSUE TITLE
 Bintray user cannot be empty!

### ISSUE THREAD

**Issue by ncworm** [novoda/bintray-release#131]
* What went wrong:
Execution failed for task ':takephoto_library:bintrayUpload'.

**Comment by StefMa** [comment]
Unfortunately we can't help you without any piece information!

But as the title suggest. Maybe you have missed to set the `bintrayUser`? 
You can set it with
```-PbintrayUser=YOUR_BINTRAY_USER_NAME` to the `gradlew` task...

**Comment by ncworm** [comment]
I have settings

**Comment by blundell** [comment]
can you paste the command you are using please?

**Comment by ncworm** [comment]
gradlew clean build bintrayUpload
-PbintrayUser=thornfish
-PbintrayKey=2950224592c6cc2e2********************
-PdryRun=false

**Comment by ataulm** [comment]
Are you doing it all in one line? Or copy and pasting it as a block with newlines in it?

**Comment by blundell** [comment]
the problem may be that it is multiple lines, add a `/` and if windows add a `^`

Like so:

Windows
```
gradlew clean build bintrayUpload ^
-PbintrayUser=thornfish ^
-PbintrayKey=2950224592c6cc2e2******************** ^
-PdryRun=false
```

Mac
```
gradlew clean build bintrayUpload \
-PbintrayUser=thornfish \
-PbintrayKey=2950224592c6cc2e2******************** \
-PdryRun=false
```

**Comment by ncworm** [comment]
You're right
