### ISSUE TITLE
android 3.0 Beta2 Unable to load class 'org.gradle.api.internal.component.Usage'

### ISSUE THREAD

**Issue by qssq** [novoda/bintray-release#133]
https://issuetracker.google.com/issues/64879142 
        classpath 'com.android.tools.build:gradle:3.0.0-beta2'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-rc-1-all.zip

**Comment by StefMa** [comment]
Which versions are you using?
You have to use. 0.5 to working with gradle 4 and up...

**Comment by blundell** [comment]
Fixed via #143
