### ISSUE TITLE
How to config 'bintray-release' if I don't want to upload source code to jcenter?

### ISSUE THREAD

**Issue by titanseason** [novoda/bintray-release#137]
How to config 'bintray-release' if I don't want to upload source code to jcenter?
But can upload javadoc

**Comment by blundell** [comment]
using `-dryRun=true` will allow you to generate the output files without uploading them

(see README)
`./gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=true`

Just uploading the javadoc automatically is not supported at the moment (but you could do this manually / open a PR).
