### ISSUE TITLE
gradle api not working 

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#139]
Gradle introduced in version 3.6 the dependencies `api` and `implementation`.
Since the android plugin 3.0 use the mechanism of `api` we have to make sure that it work.

Unfortunately it isn't working. Alle `api` declared dependencies should be contained in the generated pom file. But they aren't declared there...

Why? I think because you are using gradle wrapper 3.5. Which means the `maven plugin` don't know what to do with  `api` declared dependencies.

To fix that issue we have to update the gradle wrapper version to at least 3.6...

**Comment by tasomaniac** [comment]
Thanks for detailed explanation. Isn't that easy? If we do that, is that going to be backward compatible?

**Comment by passsy** [comment]
Upgrading to 4.1 shouldn't cause any problems. Any further has other breaking changes #138

**Comment by blundell** [comment]
fixed in https://github.com/novoda/bintray-release/pull/142 (use version `0.6.1`)
