### ISSUE TITLE
aar didn't config other  Library in pom

### ISSUE THREAD

**Issue by Werb** [novoda/bintray-release#140]
I build a android  library and dependencies other's library, but the aar build finished only config my library in pom, didn't config other  library , so when i used it , make some ClassNotFoundException, how can i solve this problem?

**Comment by StefMa** [comment]
You are using "api" to declare transitive dependencies, right?
Currently bintray-release don't support that. (See one open ticket here).
Bintray-release have to update gradle to at least 3.6...

For a quick workaround use compile

**Comment by Werb** [comment]
Please review PR #141 , thanks!

**Comment by blundell** [comment]
we now target gradle 4.2.1 in #143 which seems to be what you where asking in your latest comment, closing for now
