### ISSUE TITLE
Create sample 

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#146]
I think it would be cool if we have a sample/testing module.
We can integrate it with the ci.

I think something about:
create a test project with one simple class and a few dependencies.
Then on each commit/merge we create a release (just build the jars) and extract them. Read the pom and test if everything is correct.

So wen make sure that everything works correctly after each commit/merge

**Comment by tasomaniac** [comment]
This is of course highly encouraged and a super good idea. We're doing such a thing in the build properties plugin. Gradle has a ln api where you run whole different Gradle project within a test. It first builds the given project and then assert on some specifics.

https://github.com/novoda/gradle-build-properties-plugin

**Comment by blundell** [comment]
the original idea here was that the plugin is released with itself therefore its own demo right @xrigau?, but yes I can see the benefit of a module

**Comment by StefMa** [comment]
The problem is that this bintray-release don't use the 'active development version' of bintray-release. So we can't use itself as a demo or sample...

**Comment by StefMa** [comment]
Can maybe someone of you help me with that?!
@tasomaniac 

I've created a branch [feature/samples](https://github.com/novoda/bintray-release/tree/feature/samples) with the [samples dir](https://github.com/novoda/bintray-release/tree/feature/samples/samples).
I tried to do the same "setup" like in the mentioned [gradle-build-properties-plugin](https://github.com/novoda/gradle-build-properties-plugin/tree/master/sample).
But it's not working.

I assume that the `samples/build.gradle` can apply the 'com.novoda.bintray-release'. But it can't.
If I run (for testing) `./gradlew tasks` the output is:
> Plugin with id 'com.novoda.bintray-release' not found.
If you replace the id with the class:
> Could not get unknown property 'sourceSets' for root project 'bintray-release-samples' of type org.gradle.api.Project.

I assume that I could (with this setup) use the plugin directly and can use it in the `sample/build.gradle`. Because the `buildSrc` get evaluated (& executed) by gradle before any other script got executed. So I would expect that I can use the bintray-release plugin...
Do I assume something wrong? 🤔 

Later I want to add two samples in the samples dir.
`app` and `jvm` which uses the plugin directly from the sources...
How is that possible? 🐯

**Comment by StefMa** [comment]
Ok, did it 😅 
The only thing which was missing was the `java` or `com.android.library` plugin 🤦‍♂️

**Comment by tasomaniac** [comment]
Good to hear that. Checking out the PR now.

**Comment by StefMa** [comment]
Reopened because I want to create a android lib sample as well
