### ISSUE TITLE
Should we convert to Kotlin?

### ISSUE THREAD

**Issue by Mecharyry** [novoda/bintray-release#148]
With `Kotlin` joining the roster of officially recognised android languages we should have a **discussion** as to whether we should convert this plugin to `Kotlin`. We should do this methodically to enable continued support for our client applications so:

- What are the benefits of moving to `kotlin` over staying with what we have?
- What challenges might we face?

**Comment by StefMa** [comment]
Why **I** want to have Kotlin?
Because I can't really develop groovy :D

What challanges?
We can't access properties which aren't available any more.

Groovy lets you do something like that:
```
interface aInterface {
  stuff = 2
}

class AClazz {

   void aMethod(aInterface inter) {
       inter.NOT_AVAILABLE
   } 

}
```
☝️ this will compile!
In kotlin it will not compile...

**Comment by mr-archano** [comment]
I'm not too familiar with the implementation of this plugin but the dynamic nature of Groovy comes in handy when you need to amend extensions (for instance to add utilities to classes and configurations you don't own). So we should check whether we need to use any of this magic before proceeding (or find an alternative implementation using Kotlin).

That said the classes needed to model the internals can be safely written in Kotlin and we could even use this as an opportunity to revisit the architecture (as mentioned in previous conversations involving @StefMa too).

**Comment by tasomaniac** [comment]
I would maybe consider Kotlin in a brand new Gradle plugin because it would make it easier in the initial development phase with the help of the IDE. But I don't see any value on converting TBH.
