### ISSUE TITLE
Android: Dependencies not added to POM (Gradle 4.1, Android plugin 3.0.0)

### ISSUE THREAD

**Issue by noamtamim** [novoda/bintray-release#149]
With the updated Gradle and Android plugin, the plugin now generates POMs that don't include dependencies.
I might be doing something wrong, but I tried following your guide.

**Comment by StefMa** [comment]
Thank you for the report.
We now that and working on it.
See https://github.com/novoda/bintray-release/issues/140 or #147 

I'll keep that issue open as long it is not working on android 👍

**Comment by noamtamim** [comment]
Thanks @StefMa. And it would be really helpful if you provide a working Android sample.

**Comment by noamtamim** [comment]
I think I understand what's wrong: in Gradle 4, the "compile" directive has been split to "implementation" and "api". The plugin doesn't take this into account.

**Comment by StefMa** [comment]
Exactly. In a nutshell it is... As workaround you can still use compile.

**Comment by StefMa** [comment]
0.8.0 was just released.. Should fix that issue.
