### ISSUE TITLE
plugins is broken with gradle 3.5

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#150]
While testing #147 I found out that the plugin don't work with gradle 3.5.
As I downgraded [ThirtyInch](https://github.com/grandcentrix/thirtyinch) to gradle 3.5 I got 
```
Error:Gradle DSL method not found: 'getObjects()'
```

Gradle 3.5 was release at 10 April 2017 (see https://gradle.org/releases/).
I don't know if its worth to support it.

Android Studio already needs at least gradle 4.1 with v3.0 (see https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#update_gradle).

Pure java works without any issues on 3.5....

I recommend:
Drop the support for gradle < 4.0.
What do you think?

**Comment by tasomaniac** [comment]
Gradle 4.0+ is pretty stable and backward compatible. As you said Android also requires projects to upgrade to 4.1+.

I would vote for just supporting 4.0+ which would be much more convenient.
