### ISSUE TITLE
Skipping upload for missing file

### ISSUE THREAD

**Issue by Reginer** [novoda/bintray-release#155]
我的终端无法执行，于是我用Gradle运行的。顺序是clean  ---- build----bintrayUpload.
执行之后，在Gradle Console中提示
`Skipping upload for missing file '***\build\libs\mdm-sources.jar'.`
`Skipping upload for missing file '***\build\libs\mdm-javadoc.jar'.`
`Skipping upload for missing file '***\build\publications\release\pom-default.xml'.`
***是我的项目路径。
我需要执行哪个脚本可以生成这三个文件 ？
![image](https://user-images.githubusercontent.com/12568257/34024940-f084a7f4-e187-11e7-9a78-d4bf902bf07d.png)

**Comment by StefMa** [comment]
Hey,

can you please write your question in English?
Thanks

**Comment by HouXiaohu** [comment]
@Reginer 请问你怎么解决的（How did you solve it）

**Comment by Reginer** [comment]
@HouXiaohu  先执行 generatePomFileForReleasePublication和publishReleasePublicationToMabenLocal，再执行bintrayUpload

**Comment by HouXiaohu** [comment]
@Reginer 嗯，谢谢，是这样吗： gradlew clean build generatePomFileForReleasePublicationbintrayUpload -PbintrayUser=<BINTRAY_USER> -PbintrayKey=<BINTRAY_KEY> -PdryRun=false

**Comment by Reginer** [comment]
clean ---- build----generatePomFileForReleasePublication---publishReleasePublicationToMabenLocal---bintrayUpload

**Comment by HouXiaohu** [comment]
@Reginer  有点不明白，你的意思是 先gradlew clean 然后 gradlew build 之后在 generatePomFileForReleasePublication ....，最后在gradlew  bintrayUpload ？
