### ISSUE TITLE
Investigate multimodule projects

### ISSUE THREAD

**Issue by xrigau** [novoda/bintray-release#16]
See how the plugin would work on libraries with many modules

**Comment by StefMa** [comment]
I've done it in #153 .
In this way you can include a module into your aar.

But as in SO mentioned that is not the default and not typical for the java world.
Beside of that this issue have nothing todo with the bintray-release directly.
You can simply use the plugin and put another module into the aar/jar like I've done in #153.

I don't know what the plugin should do here?
I think it is not the responsibility of the plugin to define which other modules should be included in the aar/jar...

> What i wouldn't want - having to add the plugin to each module and configure separately EWW

I think that is "another" topic.
The plugin should not be responsible to take care of putting module into a aar/jar.
But I think we could make a better API for such cases.
Thinking about of having a top-level `build.gradle` with:
```gradle
basePublish {
    userOrg = 'novoda'
    groupId = 'novoda.multi.module'
    publishVersion = "1"
//    artifactId = 'thirtyinch'
    uploadName = 'MultiModuleSample'
    description = 'a Model View Presenter library for Android'
    website = 'https://github.com/novodoa/multimodule'
}
```
and in each module then just
```gradle
publish {
    artifactId = 'module1' // module2, module3 etc.
}
```
I will close that and create another issue with that idea...
