### ISSUE TITLE
change CI settings

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#167]
Currently we run on each PR/merge etc inly 
```
gradlew clean build
```
This should be changed with the merge of #166 

We have to change the dir to `sample` and run their
```
gradlew clean build bintrayUpload -PdryRun=true --info
```
This will build the bintray-release plugin from the current sources! and "publish" the jvm sample...

As also in #166 mentioned. We should think about a "integration test" which will **really** upload the sample to bintray.. What do you think?

**Comment by tasomaniac** [comment]
I set this up and #166 is building now with also building the sample project. 

But I believe that `integrationTests` would be better. Actually not really uploading to `bintray`. 
As you can see in other Novoda gradle plugin projects like `build-properties` or `static-analysis`, you can have an in memory sample project in a test. You can even have some tests around failure test cases to test the user sees appropriate error message etc.

**Comment by tasomaniac** [comment]
Changing the CI settings is done. I will create another issue around tests.

**Comment by tasomaniac** [comment]
@StefMa It would maybe be good to have a test PR where we have a broken sample implementation to see if Jenkins catches the errors in the sample. What do you think?

**Comment by StefMa** [comment]
@tasomaniac 
Can you maybe explain me your ci settings?
Or can we switch to travis/circleci.. whatever?!

If I go to that
https://ci.novoda.com/job/bintray-release/
and click on the latest relase I don't see the changes that the jvm-sample got testet...

**Comment by tasomaniac** [comment]
The job you posted is to check the master and do a release of the plugin itself. 

Pull Requests are built with another private job (not sure why it is private)
I basically added `gradlew clean build bintrayUpload -PdryRun=true --info` to be run from the `samples` directory as an extra step.

**Comment by StefMa** [comment]
Can you maybe find out why it's private and make it public?

Mutch better would be to switch to a CI where we can manage the build process within the Repo of course.
But making it public would be a first step...

**Comment by tasomaniac** [comment]
What about introducing `ci-prb.sh` script to run on each PR. This was the local builds and the build on the CI will run the same script, nothing else. Then it does not really matter if CI is public or not. 

The process will be publicly visible with `ci-prb.sh` What do you think?

**Comment by StefMa** [comment]
You mean we introduce this `sh` file and jenkins just execute this script?
Yeah, it's a first step. Let's do it 👍 

The problem with the private jenkins job is that I (or other contributors) can't see why it fails.
Of course we can complain "run the script locally and see what happen", but that isn't really user friendly IMO.
