### ISSUE TITLE
Skipping upload for missing file 

### ISSUE THREAD

**Issue by hebing0305** [novoda/bintray-release#178]
Skipping upload for missing file 'D:\TestDemo\AutoFit\viewautofit\build\libs\viewautofit-sources.jar'.
Skipping upload for missing file 'D:\TestDemo\AutoFit\viewautofit\build\libs\viewautofit-javadoc.jar'.
Skipping upload for missing file 'D:\TestDemo\AutoFit\viewautofit\build\publications\release\pom-default.xml'.
My app not to exist file,  Why?

**Comment by StefMa** [comment]
Which task do you run to try to publish your library?
Don't forget to call `build` or `bundleRelease` (for android projects) **before** running `bintrayUpload`.
E.g.
```
./gradlew build bintrayUpload...
```

For the pom you could also try to run the `generatePomFileForReleasePublication` task.
Does that help?

**Comment by hebing0305** [comment]
@StefMa Thanks, My English may not be very good, this is Google Translate，I added the code,run the generatePomFileForReleasePublication task. succeeded!


task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    // destinationDir = file("../javadoc/")
    failOnError false 
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}
artifacts {
    archives javadocJar
    archives sourcesJar
}

**Comment by tasomaniac** [comment]
Glad that it worked out well.
