### ISSUE TITLE
my project don‘t upload aar to bintray recently

### ISSUE THREAD

**Issue by LuckyJayce** [novoda/bintray-release#182]
my project don‘t upload aar to bintray recently
  
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.novoda:bintray-release:0.3.4'
    }

 library gradle     

    apply plugin: 'com.novoda.bintray-release'
    
    publish {
        userOrg = 'luckyjayce'
         groupId = 'com.shizhefei'
         artifactId = 'LargeImageView'
         publishVersion = '1.1.0-a6'
         desc = 'display large image,can scale and move image'
         website = 'https://github.com/LuckyJayce/LargeImageView'
    }

logout :
....
Ran lint on variant debug: 25 issues found
Ran lint on variant release: 25 issues found
Wrote HTML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/build/outputs/lint-results-debug.html
Wrote XML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/build/outputs/lint-results-debug.xml
:app:prepareDebugUnitTestDependencies
:app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:app:compileDebugUnitTestSources UP-TO-DATE
:app:assembleDebugUnitTest
:app:testDebugUnitTest UP-TO-DATE
:app:prepareReleaseUnitTestDependencies
:app:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:app:compileReleaseUnitTestSources UP-TO-DATE
:app:assembleReleaseUnitTest
:app:testReleaseUnitTest UP-TO-DATE
:app:test UP-TO-DATE
:app:check
:app:build
Skipping upload for missing file '/home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/libs/library-sources.jar'.
Skipping upload for missing file '/home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/libs/library-javadoc.jar'.
Skipping upload for missing file '/home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/publications/maven/pom-default.xml'.

BUILD SUCCESSFUL

jcenter:
https://bintray.com/luckyjayce/maven/LargeImageView

**Comment by passsy** [comment]
version `0.3.4` is pretty outdated, try `0.8.0`

**Comment by tasomaniac** [comment]
Also please have a look #96 #178 with similar problems. 
Apart from using the latest version, you need to make sure that you have a successful build and `aar` artifacts are generated.

**Comment by LuckyJayce** [comment]
still failed

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.novoda:bintray-release:0.8.0'
    }
 
   library gradle  

    publish {
        userOrg = 'luckyjayce'
        groupId = 'com.shizhefei'
        artifactId = 'LargeImageView'
        publishVersion = '1.1.0-a9'
        desc = 'display large image,can scale and move image'
        website = 'https://github.com/LuckyJayce/LargeImageView'
    }
 
    task sourcesJar(type: Jar) {
        from android.sourceSets.main.java.srcDirs
        classifier = 'sources'
    }
 
    task javadoc(type: Javadoc) {
        source = android.sourceSets.main.java.srcDirs
        classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
        // destinationDir = file("../javadoc/")
        failOnError false
    }
 
    task javadocJar(type: Jar, dependsOn: javadoc) {
        classifier = 'javadoc'
        from javadoc.destinationDir
    }
 
    artifacts {
        archives javadocJar
        archives sourcesJar
    }

log：
...
> Task :library:bintrayUpload
Skipping upload for missing file '/home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/outputs/aar/library-release.aar'.
Skipping upload for missing file '/home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/publications/release/pom-default.xml'.

> Task :app:compileDebugJavaWithJavac
注: /home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/src/main/java/com/example/lagerimage_test/SingleDemoActivity.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :app:compileReleaseJavaWithJavac
注: /home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/src/main/java/com/example/lagerimage_test/SingleDemoActivity.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :app:lint
Ran lint on variant release: 29 issues found
Ran lint on variant debug: 29 issues found
Wrote HTML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/build/reports/lint-results.html
Wrote XML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/app/build/reports/lint-results.xml

> Task :library:lint
Ran lint on variant debug: 3 issues found
Ran lint on variant release: 3 issues found
Wrote HTML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/reports/lint-results.html
Wrote XML report to file:///home/luckyjayce/AndroidStudioProjects/LargeImage/LargeImage/library/build/reports/lint-results.xml


BUILD SUCCESSFUL in 38s

jcenter:
https://bintray.com/luckyjayce/maven/LargeImageView

**Comment by DRPrincess** [comment]
I meet this situation,I  solve id by add this code,but I do not know the reason
,you can try it 。   @LuckyJayce 

```
//拷贝javadoc文件
task copyDoc(type: Copy) {
    from "${buildDir}/docs/"
    into "docs"
}
```

**Comment by krmao** [comment]
so , how to solve it ?
```
External native generate JSON release: JSON generation completed without problems
:bintrayUploadSkipping upload for missing file '/Users/maokangren/workspace/bspatch/library-bspatch/build/libs/bspatch-0.0.1-sources.jar'.
Skipping upload for missing file '/Users/maokangren/workspace/bspatch/library-bspatch/build/libs/bspatch-0.0.1-javadoc.jar'.
Skipping upload for missing file '/Users/maokangren/workspace/bspatch/library-bspatch/build/publications/release/pom-default.xml'.

```

version is 0.8.1
I want to upload aar not jar

**Comment by StefMa** [comment]
You can give https://github.com/stefma/bintray-release a try...

**Comment by krmao** [comment]
OK I will try it @StefMa ,
now I am trying by this https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450

**Comment by krmao** [comment]
hi man @StefMa , I have upload to JCenter success, 
you can see it now at [https://github.com/krmao/bspatch/blob/master/library-bspatch/build.gradle](https://github.com/krmao/bspatch/blob/master/library-bspatch/build.gradle)

with artical
[
https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450](
https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450)
[
https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450](
https://android.jlelse.eu/publishing-your-android-kotlin-or-java-library-to-jcenter-from-android-studio-1b24977fe450)
