### ISSUE TITLE
Remove deprecated props or extend `checkClosureSetup`

### ISSUE THREAD

**Issue by StefMa** [novoda/bintray-release#190]
With #181 we introduced a failing plugin if the mandatory properties aren't setup.

Since we have two deprecated properties (which have a replaced mandatory) we can get rid of that and can remove them.

OR (but I don't like that):
We could "extend" the `checkClosureSetup` that if `extension.desc` is not available check if `extension.desccription` is available.

Pro/Cons:
The first solution will maybe fail on clients because they using `version` or `description`.
But I think it is a no brainer to see why the build fail I would prefer it.
The second solution will bring some "overhead" which isn't needed IMO.

Alternative we could check if `version` or `description` is used and don't fail but give a hint that the user sees that these properties are deprecated and should be replaced...

**Comment by tasomaniac** [comment]
We should've added a `logger.warn` for the deprecated properties long time ago. Without a warning, it is impossible for users to see and replace them. 

Just like you said, since the mandatory param checker explains what is missing, it could also be fine to just remove them. We would also explain in CHANGELOG.

**Comment by StefMa** [comment]
Ok, great. I'll remove it.

Because you have asked in #181 about the description params.
According to https://github.com/bintray/gradle-bintray-plugin it is optional:
See step 4 and step 6... 

Why do you think that it was mandatory @blundell ?

**Comment by tasomaniac** [comment]
I also didn't understand the reason when he posted the line where the `desc` is defined. I think he may have thought it is mandatory because it is not marked as `@Nullable`.

**Comment by blundell** [comment]
Yeah I took all fields that where not instantiated to a value be default as mandatory.

See here, if you compare `desc` to `website`: https://github.com/novoda/bintray-release/blob/d07e6c93ff6b2d12573932372608de5593e47fcd/core/src/main/groovy/com/novoda/gradle/release/PublishExtension.groovy#L19-L21

**Comment by StefMa** [comment]
Ah ok. Thanks for explaining 👍
