### ISSUE TITLE
how can i close source?

### ISSUE THREAD

**Issue by paizxin** [novoda/bintray-release#194]
dont want to upload the sources.jar file

**Comment by StefMa** [comment]
Hey @paizxin 

currently it is *not* supported to don't upload the sources.jar.

**Comment by passsy** [comment]
You can define your own `"${variant.name}AndroidSourcesJar` task and return an empty or stripped down version.

**Comment by chouchouyu** [comment]
I wanna keep sources.jar file private too

**Comment by chouchouyu** [comment]
It seems that Jcenter don't accept The repositories  dosen't contains sources.jar

**Comment by StefMa** [comment]
This is still not supported by this plugin.
And as it got closed I don't think it will ever supported...

Anyway. This is a plugin for bintray. And you can of course publish you
library  to bintray without sources. But then, as you said, you can't link
it to jcenter...

**Comment by stfnt** [comment]
fix https://github.com/novoda/bintray-release/pull/331
