### ISSUE TITLE
release BuiltType is not uploaded to bintray

### ISSUE THREAD

**Issue by dgngulcan** [novoda/bintray-release#197]
I'm using most basic implementation as it is described in `README` and having issues with my flavors.
In my library, I log accordingly to the build type. However, when I implement my library from bintray, I the library still logs on the console. 

Do I need to specify release build? How can I prevent this?

Thanks!

#### my logging function
```
internal fun logException(exception: Exception) {
    if (BuildConfig.DEBUG) {
        exception.printStackTrace()
    }
}
```

#### inside module level `build.gradle`

    buildTypes {

        release {
            buildConfigField "Boolean", "DEBUG_MODE", "false"
       }

        debug {
            buildConfigField "Boolean", "DEBUG_MODE", "true"
        }

    }

**Comment by StefMa** [comment]
Hey,

can you please show us the configuration you use?
Normally we use the release type as default. So it shouldn't log the track.

**Comment by dgngulcan** [comment]
In my library, I also use an external library written in c++, which I build in my `build.gradle` as below. 

When I export a `release.aar`, I don't see logs but when I implement from bintray, I see the logs.
Sorry I didn't include external builds on my question.

#### bintray usage
`implementation 'com.groupname:android-sdk:1.0.2'`

#### build.gradle
```
   release {
            buildConfigField "Boolean", "DEBUG_MODE", "false"
            externalNativeBuild {
                cmake.cppFlags '-g0'
            }
        }

        debug {
            buildConfigField "Boolean", "DEBUG_MODE", "true"
            externalNativeBuild {
                cmake.cppFlags '-g'
            }
        }
```

#### push.gradle
```
apply plugin: 'com.novoda.bintray-release'
apply plugin: 'maven-publish'

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

// config doc: https://github.com/novoda/bintray-release/wiki/Configuration-of-the-publish-closure
publish {

    bintrayUser = properties.getProperty("bintray.user")
    bintrayKey = properties.getProperty("bintray.apikey")
    userOrg = 'ORG_NAME'
    groupId = 'GROUP_ID'
    artifactId = 'android-sdk'
    publishVersion = '1.0.0'
    website = 'WEBSITE_URL'
    dryRun = false

}


publishing {

    publications {
        maven(MavenPublication) {

            // Artifact properties
            groupId group
            version version
            artifactId archivesBaseName

            artifact("$buildDir/outputs/aar/${archivesBaseName}-release.aar")

            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                def configurationNames = ["releaseCompile", 'compile']

                configurationNames.each { configurationName ->
                    configurations[configurationName].allDependencies.each {
                        if (it.group != null && it.name != null) {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', it.group)
                            dependencyNode.appendNode('artifactId', it.name)
                            dependencyNode.appendNode('version', it.version)

                            //If there are any exclusions in dependency
                            if (it.excludeRules.size() > 0) {
                                def exclusionsNode = dependencyNode.appendNode('exclusions')
                                it.excludeRules.each { rule ->
                                    def exclusionNode = exclusionsNode.appendNode('exclusion')
                                    exclusionNode.appendNode('groupId', rule.group)
                                    exclusionNode.appendNode('artifactId', rule.module)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by StefMa** [comment]
You can remove the whole `publishing` block. The plugin does it for you.

Hmm don't know if that is the issue but maybe try to just remove the publishing block and try again?!
Other than that the configuration looks good 👍

**Comment by StefMa** [comment]
Just for tracking.
This is the code which should say that we want to upload the release:
https://github.com/novoda/bintray-release/blob/master/core/src/main/groovy/com/novoda/gradle/release/BintrayConfiguration.groovy#L26

**Comment by passsy** [comment]
Also notice that `website` has to be a working link. Bintray verifies this when uploading.

**Comment by dgngulcan** [comment]
I tried with another project and It is working properly with release build. 
Thank you for the information!

Closing this issue because the problem is not caused by bintray plugin.
