### ISSUE TITLE
Apply plugin only works before artifact plugin on build.gradle of module 

### ISSUE THREAD

**Issue by GuilhermeMota93** [novoda/bintray-release#198]
Hey.

I was playing around with the plugin and encountered an issue I wasn't expecting. I managed to get around it, but it then caused (I think) another issue.

**Issue 1)**

When setting up, as per the README (https://github.com/novoda/bintray-release/blob/master/README.md) I was trying to add the 

`apply plugin: 'com.novoda.bintray-release' `

after my 

`apply plugin: 'com.android.library'`

But when syncing, got the Gradle error:

`Error:Exception thrown while executing model rule: PublishingPlugin.Rules#addConfiguredPublicationsToProjectPublicationRegistry(ProjectPublicationRegistry, PublishingExtension, ProjectIdentifier)`

After a while of wondering,  I tried:

`apply plugin: 'com.novoda.bintray-release' `
`apply plugin: 'com.android.library'`

and the following buildscript with classpath immediately after as:
`classpath 'com.novoda:bintray-release:0.8.0'`

This allowed to sync nicely. 

**Which led me to issue 2):**

Trying to run `bintrayUpload`, after running my tests and all passed, it fails with:

> Publication release not found in project :[MODULE-NAME].

> Task :[MODULE-NAME]:bintrayUpload FAILED
:[MODULE-NAME]:bintrayUpload: Could not find publication: release.

>FAILURE: Build failed with an exception.

>* What went wrong:
>Execution failed for task ':[MODULE-NAME]:bintrayUpload'.
> java.lang.NullPointerException (no error message)

Just thought I would mention the 2 issues together as it may relate, more than happy to open different ones.

**More details:**

My Gradle versions is:

$ gradle --version
Gradle 4.4.1

and Android `build.gradle` with

`classpath 'com.android.tools.build:gradle:3.0.1'`

**Comment by GuilhermeMota93** [comment]
So **step 1** from before still remains, added the plugin before my `apply plugin: 'com.android.library'` and it seems to be working (would like to understand why it was needed like that though...)

I now managed to publish to my binTray account, but I can't seem to be adding the `Download` bit (I'm missing the `pom` file and/or the publish to Maven, but I can't seem to get it to work). 

Here's what I did:

i) My publish task on my module `build.gradle` now looks like this:
>publish {
    groupId = System.properties.getProperty("groupId", "")
    artifactId = System.properties.getProperty("artifactId", "")
    publishVersion = System.properties.getProperty("publishVersion", "")
    website = System.properties.getProperty("website", "")
    uploadName = System.properties.getProperty("uploadName", "")
}

ii) I then run the following command

> ./gradlew clean build publish -DgroupId=[GROUP_ID] -DpublishVersion=[VERSION] -DartifactId=[ARTIFACT_ID] -DuploadName=[PACKAGE_NAME] -Dwebsite=[WEBSITE] bintrayUpload -PbintrayUser=[BINTRAY_USER] -PbintrayKey=[BINTRAY_KEY] -PdryRun=false

With this I can see my project on binTray, with the correct version and apparently okay. Just missing the `Download` section which I can't seem to understand why is not showing. 

Any ideas on what I might be missing?

Thanks in advance!

**Comment by StefMa** [comment]
Hey @GuilhermeMota93 

> would like to understand why it was needed like that

If you apply a Gradle plugin and run a task Gradle will first execute some code for each applied plugin in a sequence how they are applied.
Since bintray-release depends on some basic setup for the android-library (or java-library) plugin it has to be applied *after* that.

> Just missing the Download section

What do you mean with "Download section"? 🤔 
You can find a fully example how it should look like on Bintray.com here:
https://bintray.com/novoda/maven/bintray-release
Which part do you miss in your project?

**Comment by GuilhermeMota93** [comment]
Hey @StefMa , thank you for coming back to me so fast, really appreciate it.

Regarding your explanation, 

> Since bintray-release depends on some basic setup for the android-library (or java-library) plugin it has to be applied after that.

This does make sense, and it is what I was expecting to happen, but I could only get it to work by adding it _before_. As such:
> apply plugin: 'com.novoda.bintray-release' // this should be after
apply plugin: 'com.android.library'

Trying to add it after (like this)

>apply plugin: 'com.android.library'
apply plugin: 'com.novoda.bintray-release' //this should be here, but gives error!

gives the Gradle error

> Error:Exception thrown while executing model rule: PublishingPlugin.Rules#addConfiguredPublicationsToProjectPublicationRegistry(ProjectPublicationRegistry, PublishingExtension, ProjectIdentifier)

All of this, on the `build.gradle` of a module.

Apologies on the `Download` bit, what I meant was the `Maven build settings` is missing on my project. I thought it was the download section as I was counting it to be in the same position, but in the example you show, the Maven settings sits on top of the Download (which is also empty, so that seems to be expected). 

To clarify, I meant the `Maven build settings` is missing on my project.

**Comment by mr-archano** [comment]
Hi @GuilhermeMota93 are you still facing this issue? Could you please post the version of Gradle and Android Gradle Plugin you are using? 
Additionally would it be possible to fork the sample to actually reproduce your issue?

**Comment by GuilhermeMota93** [comment]
Hey @mr-archano !

After revisiting this issue and doing some digging, I managed to get it to work by setting it up like this in the **build.gradle** of my module:

```
apply plugin: 'com.novoda.bintray-release' //has to be BEFORE 'com.android.library'
apply plugin: 'com.android.library'
//...more plugins

apply plugin: 'maven-publish' //adding maven-publish

//and the dependency right after the maven-publish
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.novoda:bintray-release:0.8.0'
    }
}

//...

publish {
    userOrg = 'myOrg'
    groupId = 'com.myProj'
    artifactId = 'my-proj-artifact'
    publishVersion = '0.0.1'
    desc = 'Description here'
    website = 'https://my.url.com'

    publishing {
        publications {
            MyPub(MavenPublication) {
                groupId 'com.myProj'
                artifactId 'my-proj-artifact'
                version '0.0.1'

                //don't forget to add bundleRelease
                artifact bundleRelease

            }
        }
    }
    publications = ['MyPub']
}

//...
```

Alternatively, in order to allow this to work more dynamically, I'm using **System.properties.getProperty()** to set my **publish** configs.

E.g:
```
publish {
   def groupProjectID = System.properties.getProperty("groupProjectID", "")
   groupId = groupProjectID

   //...other configs

  //and then I can reuse it in the publishing as
  publishing {
        publications {
            MyPub(MavenPublication) {
                
                groupId groupProjectID

                //...other configs

            }
        }
    }
    publications = ['MyPub']

}
```
I would then call this in the command line (or custom script):

`./gradlew clean build publish -DgroupProjectID=[MY_GROUP_PROJECT_ID] bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false`

My Gradle version is 4.4 and Android Plugin version is 3.0.1.

This is now working as expected! 👍

**Comment by SheharyarEjaz** [comment]
Just add it in built.gradle (Project level)  
           
        classpath 'com.novoda:bintray-release:0.8.0'

under 

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.novoda:bintray-release:0.8.0'
    }
Note:
       make sure you are adding this dependency at Project level gradle
