### ISSUE TITLE
Add Bintray requirements to README

### ISSUE THREAD

**Issue by hzsweers** [novoda/bintray-release#20]
This is both an issue and a question. I'm relatively new to creating my own library and uploading to Bintray, and it seems like it requires some prior work before this plugin can start working. I've created an account and set up the plugin with the appropriate information (including the API key), and while says build/upload were successful, nothing ever shows up on bintray.

Are there other steps that need to be done before-hand to make uploads work? Would it be possible to add some checks for this in the plugin? As I mentioned, it's reporting successful uploads but not actually working, so it would be nice if it recognized this.

Here's my gradle output. It's a two-part annotation processor project. The processor ('compiler') is a java library only, while the 'api' is an android library project. 

```
$ gw bintrayUpload              
:api:androidJavadocs UP-TO-DATE
:api:androidJavadocsJar UP-TO-DATE
:api:androidSourcesJar UP-TO-DATE
:api:generatePomFileForMavenPublication
:api:publishMavenPublicationToMavenLocal
:api:bintrayUpload
:compiler:generatePomFileForMavenPublication
:api:compileLint
:api:copyReleaseLint UP-TO-DATE
:api:mergeReleaseProguardFiles UP-TO-DATE
:api:preBuild UP-TO-DATE
:api:preReleaseBuild UP-TO-DATE
:api:checkReleaseManifest
:api:prepareReleaseDependencies
:api:compileReleaseAidl UP-TO-DATE
:api:compileReleaseRenderscript UP-TO-DATE
:api:generateReleaseBuildConfig UP-TO-DATE
:api:generateReleaseAssets UP-TO-DATE
:api:mergeReleaseAssets UP-TO-DATE
:api:generateReleaseResValues UP-TO-DATE
:api:generateReleaseResources UP-TO-DATE
:api:packageReleaseResources UP-TO-DATE
:api:processReleaseManifest UP-TO-DATE
:api:processReleaseResources UP-TO-DATE
:api:generateReleaseSources UP-TO-DATE
:api:compileReleaseJava UP-TO-DATE
:api:processReleaseJavaRes UP-TO-DATE
:api:packageReleaseJar UP-TO-DATE
:api:compileReleaseNdk UP-TO-DATE
:api:packageReleaseJniLibs UP-TO-DATE
:api:packageReleaseLocalJar UP-TO-DATE
:api:packageReleaseRenderscript UP-TO-DATE
:api:bundleRelease UP-TO-DATE
:compiler:compileJava UP-TO-DATE
:compiler:processResources UP-TO-DATE
:compiler:classes UP-TO-DATE
:compiler:jar UP-TO-DATE
:compiler:javadocJar UP-TO-DATE
:compiler:sourcesJar UP-TO-DATE
:compiler:publishMavenPublicationToMavenLocal
:compiler:bintrayUpload

BUILD SUCCESSFUL

Total time: 4.549 secs
```

**Comment by blundell** [comment]
You're missing a few paramaters:

-PbintrayUser=BINTRAY_USERNAME 
-PbintrayKey=BINTRAY_KEY 
-PdryRun=false

so the full command is:

`gw clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false`

(see readme https://github.com/novoda/bintray-release/blob/master/README.md)

**Comment by hzsweers** [comment]
I'm not missing them, I've just specified them directly in the plugin.

```groovy
publish {
    userOrg = 'pandanomic'
    groupId = 'io.sweers'
    artifactId = <project>
    version = '1.0.0'
    description = <description>
    website = rootProject.ext.siteUrl
    bintrayUser = rootProject.ext.bintrayUser
    bintrayKey = rootProject.ext.bintrayKey
    autoPublish = false
}
```

**Comment by blundell** [comment]
where is the dryRun = false param?

**Comment by blundell** [comment]
where is the dryRun = false param?

**Comment by hzsweers** [comment]
Ah, that's the problem. I misread the wiki before and thought it said that it was false *by default*. Apologies, thanks for getting back to me so quickly :)

**Comment by blundell** [comment]
:+1:
