### ISSUE TITLE
Is uploading snapshot builds to OJO supported?

### ISSUE THREAD

**Issue by hendraanggrian** [novoda/bintray-release#201]
I'm still pretty new to [OJO](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org#DeployingSnapshotstooss.jfrog.org-GettingStartedwithOJO) and wondering if it is supported with this plugin?

**Comment by StefMa** [comment]
Great question @hendraanggrian 

No, this is not possible.
bintray-release is just here to publish artifacts to bintray. Not to OJO.
But since OJO is a simple artifactory you can use [this](https://github.com/StefMa/ArtifactoryPublish) plugin which can help you to deploy to OJO.

Hope that helps?!

**Comment by hendraanggrian** [comment]
Thanks for clarifying! I'll try that plugin later, on account that it is an extension of this plugin.
