### ISSUE TITLE
How should I configure my project with multiple modules?

### ISSUE THREAD

**Issue by qingmei2** [novoda/bintray-release#204]
Hi.

I try to upload all modules.

![bcb58fef77fe3b5fae443211122efea8](https://user-images.githubusercontent.com/21142152/37903709-732d6996-312b-11e8-8bf3-d9e3cdc5246a.jpg)

 I have a simple configuration for each of my modules and it is BUILD SUCCESSFUL  by:

> ./gradlew clean build bintrayUpload -PbintrayUser=xxx -PbintrayKey=xxx -PdryRun=false

But I get a problem,  I can't get the latest version，because only one module was successfully uploaded to Jcenter, and other libraries cannot be successfully compile:

> // last version is beta3
http://jcenter.bintray.com/com/github/qingmei2/rximagepicker/
// last version is beta3
http://jcenter.bintray.com/com/github/qingmei2/rximagepicker_extension/
// last version is beta6
http://jcenter.bintray.com/com/github/qingmei2/rximagepicker_extension_zhihu/

 But the it looks no problem on the website (Maybe..):

![image](https://user-images.githubusercontent.com/21142152/37903919-5aa18050-312c-11e8-9b09-ce4b04240766.png)

I think it because my configuration error，but I don't know how should I configure correctly with multiple modules. 

Below is the configuration code for each of my modules——Only the artifactId is different：

```groovy
publish {
    userOrg = 'xxx'
    groupId = 'com.github.qingmei2'
    artifactId = 'rximagepicker'  // 'rximagepicker_extension'/rximagepicker_extension_xxx''
    publishVersion = 0.1.0-beta5
    desc = 'xxx.'
    website = 'xxx'
}
```

and The dependency between them is：
> rximagepicker

> rximagepicker_extension   
   implementation 'rximagepicker'

> rximagepicker_extension_xx
  implementation 'rximagepicker_extension'

**Comment by passsy** [comment]
You can checkout [ThirtyInch](https://github.com/grandcentrix/ThirtyInch) as an example. Might look like a lot duplicated code which can be reduced with a [helper function](https://github.com/grandcentrix/ThirtyInch/pull/141/)

**Comment by mr-archano** [comment]
If you apply the release plugin to each of your module independently then you should try to upload your modules one at a time `:$moduleName:bintrayUpload` instead of the plain `bintrayUpload`. Could you please paste the output of `./gradlew bintrayUpload --dry-run -PbintrayUser=xxx -PbintrayKey=xxx -PdryRun=false`?

**Comment by qingmei2** [comment]
@passsy 
thanks for your help. :smile:

I try to fork your [ThirtyInch](https://github.com/grandcentrix/ThirtyInch)，and try to stay consistent with your configuration.

It gives me a good idea for reducing duplicated code, but not solving the problem.

**Comment by qingmei2** [comment]
@mr-archano 
thanks for your help. 

Strangely, I still succeed by upload my modules one at a time, but still only one module can be successfully compile.

I have tried to delete and re-upload the library to the jcenter, and hope this behavior can bring good results.:joy:

**Comment by StefMa** [comment]
@qingmei2 can we close that issue? 
Is that fixed "for now"?
If it happen again feel free to open a new issue 👍

**Comment by qingmei2** [comment]
@StefMa 
Okay, thanks for your help.
