### ISSUE TITLE
How to upload mixed code

### ISSUE THREAD

**Issue by xiaoleiwei** [novoda/bintray-release#206]
I want to upload mixed code to jcenter, can?

**Comment by StefMa** [comment]
What do you mean with "mixed code"?

**Comment by xiaoleiwei** [comment]
proguard or obfuscated code

**Comment by StefMa** [comment]
What is the usecase of deploying a obfuscated library?
Haven't tested it yet, but it should work.
But then you need a documentation for your library based on the progaurd-output-files  which says somethinglike:
```
This class can be used to create a Version
class X {
}

Simply call `y` to get the generated version
public String y() {
...
}
```
Does it make sense somehow? 😂 
Don't think so..

If you want to provide a proguard-file with the setup for your library read this:
https://robopress.robotsandpencils.com/how-to-use-proguard-with-your-android-library-c0a2b2b5d3b

But then your code will be - of course - not obfuscated uploaded to bintray...

**Comment by AigeStudio** [comment]
I have same question for Java library. Is there any way to config Proguard easier for Java library use bintray-release?
