### ISSUE TITLE
Config bintray.apikey and user in local.properties

### ISSUE THREAD

**Issue by huhuang03** [novoda/bintray-release#208]
Some other releasing helper plugin do this, do you think it's a good or bad idea.
Will you add this feature?

**Comment by StefMa** [comment]
What do you mean exactly? 🤔
We should create the local.properties for you and out a key in it?

**Comment by huhuang03** [comment]
I'm sorry, my english is poor .
I mean have some config in local.properties like this.
```
bintray.apikey=My bintray api key
bintray.user=My bintray user
```
So I can run
```
./gradlew clean build bintrayUpload
```
without provide `-PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY`

**Comment by mr-archano** [comment]
@huhuang03 I would recommend to use another approach, as it's really easy to script what you want in your `build.gradle`, something like:
```
File localProperties = rootProject.file('local.properties')
if (localProperties.exists()) {
  Properties properties = new Properties()
  properties.load(new FileInputStream(file))
  project.ext.bintrayUser = properties['bintray.user']
  project.ext.bintrayKey = properties['bintray.apiKey']
}
```

That said we could try provide a way to set those properties from the extension (or the task), I will note it down as a feature request.

**Comment by huhuang03** [comment]
@StefMa @mr-archano Thx!
Yes, config in [~/.gradle/](http://mrhaki.blogspot.com/2015/10/gradle-goodness-setting-global.html) is the best practice, which I didn't know before.  

This is not a good feature request!
