### ISSUE TITLE
Adding <type> to generated POM file <dependency> elements for AARs

### ISSUE THREAD

**Issue by andrewlewis** [novoda/bintray-release#212]
Is it possible to have the release plugin include `<type>` elements under `<dependency>` elements in generated POM files? Here is an [example](https://bintray.com/google/exoplayer/download_file?file_path=com%2Fgoogle%2Fandroid%2Fexoplayer%2Fexoplayer-hls%2F2.8.1%2Fexoplayer-hls-2.8.1.pom) of a published artifact's POM file where we'd like to include them.

Background: I'm trying to use `mvn dependency:copy-dependencies` to download an artifact with all its dependencies. With the current generated POM files, maven fails to download JARs for dependencies, but when I add `<type>aar</type>` to dependencies in the POM file it correctly downloads the AAR. Thanks!

**Comment by w4-hyungsun** [comment]
It seems to overlap with #140 and #149 .
Is there any workaround for this?
