### ISSUE TITLE
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

### ISSUE THREAD

**Issue by luhuanxml** [novoda/bintray-release#213]
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

------
What can I do

**Comment by luhuanxml** [comment]
Now I find it ,I can not use  
```distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip```
must use
```distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip```

**Comment by StefMa** [comment]
Thank you. We are aware of this. See #177

**Comment by luhuanxml** [comment]
Ok,I have used gradle4.4 . It’s great.

On Jun 9, 2018, at 3:20 PM, Stefan M. <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #213<https://github.com/novoda/bintray-release/issues/213>.

**Comment by nikhilbansal064** [comment]
minimum supported gradle version for Android studio 3.2 is 4.6,SO cant make it 4.4.

**Comment by Siddharth3** [comment]
> Now I find it ,I can not use
> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`
> must use
> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

i am getting the same problem and when i am changing the gradle version from 4.6 to 4.4, getting error "Minimum supported Gradle version is 4.6. Current version is 4.4."

**Comment by luhuanxml** [comment]
3.1.4tool

发自我的 iPad

在 2018年9月30日，下午11:07，Siddharth Sahni <notifications@github.com<mailto:notifications@github.com>> 写道：


Now I find it ,I can not use
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip<http://services.gradle.org/distributions/gradle-4.6-all.zip>
must use
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip<http://services.gradle.org/distributions/gradle-4.4-all.zip>

i am getting the same problem and when i am changing the gradle version from 4.6 to 4.4, getting error "Minimum supported Gradle version is 4.6. Current version is 4.4."

**Comment by luhuanxml** [comment]
classpath. gradle tool 3.1.4 is ok

发自我的 iPad

在 2018年9月30日，下午11:07，Siddharth Sahni <notifications@github.com<mailto:notifications@github.com>> 写道：


Now I find it ,I can not use
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip<http://services.gradle.org/distributions/gradle-4.6-all.zip>
must use
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip<http://services.gradle.org/distributions/gradle-4.4-all.zip>

i am getting the same problem and when i am changing the gradle version from 4.6 to 4.4, getting error "Minimum supported Gradle version is 4.6. Current version is 4.4."

**Comment by mecoFarid** [comment]
Anything yet? Upgrading Android Studio is just hell.

**Comment by mr-archano** [comment]
We have found a quick solution to the problem: https://github.com/novoda/bintray-release/compare/ISSUES/177

I am in the middle of checking whether the POM file is generated as expected, but there should be a PR open in a couple of hours.

**Comment by KishanViramgama** [comment]
using android studio 3.2 

> Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

**Comment by mr-archano** [comment]
@hieonn that solution you linked sounds wrong. Maybe you are fixing the issue at configuration time but you won't be able to generate the right artifacts, as the plugin might not recognise that as an Android module.
What version of Gradle are you using?

**Comment by RurioLuca** [comment]
I confirm the problem with versions 0.8.0 - 0.8.1 I get:
Causes: com.novoda.gradle.release.AndroidLibrary $ LibraryUsage.getDependencyConstraints () Ljava / util / Set;

I have some other repositories that I updated last week and your library worked perfectly.
The only difference I can notice is that I do not include any bookshelves on the latter.
https://github.com/RurioLuca/QrCardParsing


@mr-archano

**Comment by zihang740** [comment]
classpath 'com.novoda:bintray-release:0.8.1'
Fail:
   classpath 'com.android.tools.build:gradle:3.2.1'
   distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
Success:
  classpath 'com.android.tools.build:gradle:3.1.0'
  distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
Cause:
  Incompatible gradle-4.4-all.zip

**Comment by zihang740** [comment]
classpath 'com.novoda:bintray-release:0.8.1'
Fail:
classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip
Success:
classpath 'com.android.tools.build:gradle:3.1.0'
distributionUrl=https://services.gradle.org/distributions/gradle-4.4-all.zip
Cause:
Incompatible gradle-4.6-all.zip

**Comment by zainriaz** [comment]
> I found the the answer for the problem com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/S
> 
> Refer to https://stackoverflow.com/a/52726149/1349104
> The the import part is the order of apply
> 
> You don't need to change anything. Cheer up guys!

thanks buddy for the complete solution!! Cheers

**Comment by jmarceli** [comment]
@hieonn thanks for pointing out a solution. It is worth noting that modifications should be done inside `build.gradle (Module: capacitor-android)`.

**Comment by kushalmahapatro** [comment]
This solution worked for me:
As Bintray has fixed the issue in its new release i.e. 0.9 so adding that in build.gradle (project) files removes the error.

classpath 'com.novoda:bintray-release:0.9'

**Comment by CurtesMalteser** [comment]
> I found the the answer for the problem com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/S

It's incredible that switching this two lines solved the problem.
Thank you

**Comment by CurtesMalteser** [comment]
> I found the the answer for the problem com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/S
> 
> Refer to https://stackoverflow.com/a/52726149/1349104
> The the import part is the order of apply
> 
> You don't need to change anything. Cheer up guys!

It's incredible that switching this two lines solved the problem.
Thank you

**Comment by faza76** [comment]
Thank YOU!!

**Comment by zainriaz** [comment]
> I found the the answer for the problem com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/S
> 
> Refer to https://stackoverflow.com/a/52726149/1349104
> The important part is the order of apply
> 
> You don't need to change anything. Cheer up guys!

Thanks Sir, the solution get worked, saved my day.
