### ISSUE TITLE
com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

### ISSUE THREAD

**Issue by Reginer** [novoda/bintray-release#215]
android studio 3.1.3 
gradle 4.6
novoda 0.8.1

![image](https://user-images.githubusercontent.com/12568257/41757356-3d689762-7614-11e8-9bda-cacead4d2903.png)

**Comment by StefMa** [comment]
We are aware of this.
See #213 and #177
