### ISSUE TITLE
Allow version to be provided as a command line arg

### ISSUE THREAD

**Issue by ojw28** [novoda/bintray-release#22]
Currently, it's necessary to set the version in build.gradle, like:

```
publish {
  ....
  version = 'r1.2.3'
}
```

It would be nice if it were possible to specify it using -Pversion=r1.2.3 on the command line instead, so that it's not necessary to update the build.gradle every time you want to do a release.

**Comment by xrigau** [comment]
@ojw28 this will be implemented once #23 gets merged

**Comment by xrigau** [comment]
Thanks for raising the issue btw! :+1:

**Comment by blundell** [comment]
Fixed by #23 and released as `0.2.8` https://github.com/novoda/bintray-release/releases/tag/0.2.8

**Comment by mr-archano** [comment]
:sparkles: neat!
