### ISSUE TITLE
Documentation link redirects back to same github page

### ISSUE THREAD

**Issue by jksym** [novoda/bintray-release#221]
I'm trying to find documentation for defining a custom publication. 

There's a link in README.md that redirects back to the same page. 
https://github.com/novoda/bintray-release/wiki

Thanks!

**Comment by StefMa** [comment]
It seems somewhere have removed he wiki without updating the README.
Anyway.
You can create your own publication which is [described here](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:publications) and set it as an `array` as `publications` to the `publish` extensions.

Like 
```groovy
publish {
  // All the config
  publications = ['yourCustomPublicationName']
```

Does this help?

**Comment by mr-archano** [comment]
@jksym sorry for the inconvenience, I have recently disabled the wiki by mistake while tidying up the settings of the repo. It should be fixed now.
