### ISSUE TITLE
Should userOrg be the username if I don't have an organisation?

### ISSUE THREAD

**Issue by Muddz** [novoda/bintray-release#223]

**Comment by StefMa** [comment]
Yes, the userOrg is the username if you don't have a organisation 👍
The naming is here indeed a little bit confusing...

Do you think that should be improved im some way?

**Comment by Muddz** [comment]
I think there should be these seperate attitrubtes

`organisationName` - When we want to publish on behalf of an organisation
`userName` - for people with personal account

`packageName` - So the package name is not derived from `artifactId` which I suspect it does. This can be problematic, if you change the package name manually later and publish again. This will result in a whole new package being published because the name from `artifactId` isn't there anymore

**Comment by Muddz** [comment]
Example:

1) Fist time publish

  artifactId = 'mylibrary' 
  publishVersion = '1.0.0'

2) Now I look in the package list of my Bintray account and the package name is "mylibrary"

3) I change that to "Android - Mylibrary" with uppercase 

4) I publish version 1.0.1 with these attributes

  artifactId = 'mylibrary' 
  publishVersion = '1.0.1'

5) Now a whole new package is published again with its packages title "mylibrary"

**Comment by Muddz** [comment]
@StefMa What is you take on my feedback?

**Comment by StefMa** [comment]
Thanks for the feedback.
I'll investiage in it if it make sense and will implement it maybe in https://github.com/stefma/bintray-release
