### ISSUE TITLE
Is there anyway to avoid to manually type the username and key everytime?

### ISSUE THREAD

**Issue by Muddz** [novoda/bintray-release#224]

**Comment by StefMa** [comment]
The username and key can be set by any gradle property.
Means you could for example add the name and the key to your GRADLE_HOME/gradle.properties. Then it will it read from there and you don't have to put it to the command line each time you want to publish an artifact. 

See the gradle guides for more information about it.

**Comment by mr-archano** [comment]
@Muddz it's not recommended to embed sensitive information in your buildscript, so if you want to avoid the hassle of doing that you should follow the suggestion above, or another couple of alternatives:
- add those values in `gradle.properties` in the root folder of your project, but ensure the file is not checked in your git history
- the plugin extension exposes both [`bintrayUser` and `bintrayKey`](https://github.com/novoda/bintray-release/blob/master/core/src/main/groovy/com/novoda/gradle/release/PublishExtension.groovy#L39-L41), meaning you can do:
```
publish {
    ...
    bintrayUser = readBintrayUser()
    bintrayKey = readBintrayKey()
}
```

where `readBintrayUser()` and `readBintrayKey()` would implement your additional logic to fetch the values - for instance - from an unchecked properties file, like `local.properties`.
