### ISSUE TITLE
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set; 

### ISSUE THREAD

**Issue by SpringSmell** [novoda/bintray-release#227]
after the update android studio 3.2 unable to compile.
`（1）WARN - ect.sync.idea.ProjectSetUpTask -Cause:com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set; `
`（2）INFO - e.project.sync.GradleSyncState - Gradle sync failed: Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;`

**Comment by mr-archano** [comment]
Duplicated of #177
