### ISSUE TITLE
	 There are no files yet for this version.

### ISSUE THREAD

**Issue by miaoMiaoDaShi** [novoda/bintray-release#233]
![tim 20181016180252](https://user-images.githubusercontent.com/22437662/47008940-daf61180-d16d-11e8-9429-f0a5156246b8.png)

**Comment by mr-archano** [comment]
@miaoMiaoDaShi could you please give more details about the issue? Like:
- version of the plugin you are using
- version of Gradle that you are using
- build output
- repro steps

Unfortunately a screenshot is not very helpful in this case.

**Comment by miaoMiaoDaShi** [comment]
plugin version 0.8.0
gradle version 4.4

BUILD SUCCESSFUL 
but show 
![tim 20181017165207](https://user-images.githubusercontent.com/22437662/47074562-3affbd00-d22d-11e8-984a-30ee4334399d.png)

**Comment by miaoMiaoDaShi** [comment]
@StefMa


D:\MyAndroid\MiaoCamera>gradlew clean build bintrayUpload -PbintrayUser=********* -PbintrayKey=********* -PdryRun=false
Parallel execution with configuration on demand is an incubating feature.

> Configure project :app 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

> Configure project :library 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configu
rations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configu
rations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configu
rations.html
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'and
roidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configu
rations.html
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configu
rations.html

> Configure project :miaocameralibrary 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

> Task :app:lint 
Ran lint on variant debug: 4 issues found
Ran lint on variant release: 4 issues found
Wrote HTML report to file:///D:/MyAndroid/MiaoCamera/app/build/reports/lint-results.html
Wrote XML report to file:///D:/MyAndroid/MiaoCamera/app/build/reports/lint-results.xml

> Task :library:bintrayUpload 
Skipping upload for missing file 'D:\MyAndroid\MiaoCamera\library\build\libs\library-sources.jar'.
Skipping upload for missing file 'D:\MyAndroid\MiaoCamera\library\build\libs\library-javadoc.jar'.
Skipping upload for missing file 'D:\MyAndroid\MiaoCamera\library\build\outputs\aar\library-release.aar'.
Skipping upload for missing file 'D:\MyAndroid\MiaoCamera\library\build\publications\release\pom-default.xml'.

> Task :library:compileDebugJavaWithJavac 
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: D:\MyAndroid\MiaoCamera\library\src\main\api21\com\google\android\cameraview\Camera2.java使用了未经检查或不安全的操
作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :library:extractDebugAnnotations 
Warning: com.google.android.cameraview.CameraView.Flash: The typedef annotation should have @Retention(RetentionPolicy.
SOURCE)

> Task :library:compileReleaseJavaWithJavac 
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: D:\MyAndroid\MiaoCamera\library\src\main\api21\com\google\android\cameraview\Camera2.java使用了未经检查或不安全的操
作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :library:extractReleaseAnnotations 
Warning: com.google.android.cameraview.CameraView.Flash: The typedef annotation should have @Retention(RetentionPolicy.
SOURCE)

> Task :library:lint 
Ran lint on variant release: 27 issues found
Ran lint on variant debug: 27 issues found
Wrote HTML report to file:///D:/MyAndroid/MiaoCamera/library/build/reports/lint-results.html
Wrote XML report to file:///D:/MyAndroid/MiaoCamera/library/build/reports/lint-results.xml

> Task :miaocameralibrary:lint 
Ran lint on variant debug: 20 issues found
Ran lint on variant release: 20 issues found
Wrote HTML report to file:///D:/MyAndroid/MiaoCamera/miaocameralibrary/build/reports/lint-results.html
Wrote XML report to file:///D:/MyAndroid/MiaoCamera/miaocameralibrary/build/reports/lint-results.xml


BUILD SUCCESSFUL in 43s
175 actionable tasks: 168 executed, 7 up-to-date

**Comment by mr-archano** [comment]
@miaoMiaoDaShi there's something wrong with your project. The artifacts are not generated (this might not be related to the release plugin at all), see:
```
Skipping upload for missing file 'D:\MyAndroid\MiaoCamera\library\build\libs\library-sources.jar'.
```

Try to disable the parallel build support, as you can see how the `bintrayUpload` task is execute before the compilation tasks for instance.

**Comment by miaoMiaoDaShi** [comment]
That's true,Thank you!

**Comment by StefMa** [comment]
Another - probably better solution - would be to add a dependency between these tasks:
```
bintrayUpload.dependsOn(build)
```
