### ISSUE TITLE
How to use the SNAPSHOT version?

### ISSUE THREAD

**Issue by r17171709** [novoda/bintray-release#234]
> I want to use the version of bintray-release 0.8.1-SNAPSHOT. I have already add classpath and repositories in gradle setting, but something is wrong. So how to fix this issue ?

![Image of bug](http://pgru62ka2.bkt.clouddn.com/bug.jpg)

**Comment by StefMa** [comment]
You put the repository to the **dependencies repository**. Not to the **buildscript repository**.
So it should be:
```groovy
buildscript {
  repositories {
    // Put this snapshot maven repo in
  }
  dependencies {
     classpath "com.novoda..."
  }
}
```

**Comment by mr-archano** [comment]
Sorry @StefMa but that is incorrect. The snapshot repo needs to be in the buildscript block, as it is a buildscript dependency.

@r17171709 I think the issue is with the name of the artifact, it should be just [`SNAPSHOT-6`](https://bintray.com/novoda/snapshots/bintray-release/SNAPSHOT-6):
```
classpath 'com.novoda:bintray-release:SNAPSHOT-6'
```

**Comment by r17171709** [comment]
@mr-archano @StefMa Thank you
