### ISSUE TITLE
SNAPSHOT-6 error

### ISSUE THREAD

**Issue by nyssance** [novoda/bintray-release#236]
Android Studio 3.2.1
kotlin 1.2.71
gradle 4.10.2
'com.novoda:bintray-release:SNAPSHOT-6'

* What went wrong:
Receiver class com.novoda.gradle.release.AndroidLibrary$LibraryUsage does not define or inherit an implementation of the resolved method abstract getGlobalExcludes()Ljava/util/Set; of interface org.gradle.api.internal.component.UsageContext.

**Comment by mr-archano** [comment]
That issue (#177 & #179) is not solved yet. The last snapshot solved an issue for **Java projects**. I am currently working on a solution, keep an eye on the coming days.
