### ISSUE TITLE
Please help me!Connection to https://api.bintray.com refused

### ISSUE THREAD

**Issue by 103945089** [novoda/bintray-release#240]
i keep uploading my code into bintray for like several months,  but since a week ago . i keep getting failed erro message 
org.apache.http.conn.HttpHostConnectException: Connection to https://api.bintray.com refused

please help me out

**Comment by mr-archano** [comment]
@103945089 sorry but what you posted looks like an issue with your setup, as the connection to Bintray is failing for some reason. Without a stacktrace and providing repro steps we can't help you more.

Also please keep in mind that this is not the right place to answer this kind of questions. We use GitHub issues to discuss bugs and improvements strictly related to the plugin. I would encourage you to post your question on stackoverflow or similar instead.

**Comment by 103945089** [comment]
> @103945089 sorry but what you posted looks like an issue with your setup, as the connection to Bintray is failing for some reason. Without a stacktrace and providing repro steps we can't help you more.
> 
> Also please keep in mind that this is not the right place to answer this kind of questions. We use GitHub issues to discuss bugs and improvements strictly related to the plugin. I would encourage you to post your question on stackoverflow or similar instead.

ok，thanks anyway 。 i ll try

**Comment by ForLovelj** [comment]
@103945089  I have the same problem today. Have you solved it?

**Comment by 103945089** [comment]
> @103945089 I have the same problem today. Have you solved it?

Yes, turns out what cause is my network status. try vpn . but remember to set AndroidStudio http and http ProxySettings

**Comment by ForLovelj** [comment]
@103945089 Thank you very much! AndroidStudio needs to set up proxy, and before that, I just turned on the VPN!
