### ISSUE TITLE
Javadoc prevent failOnError

### ISSUE THREAD

**Issue by HugoGresse** [novoda/bintray-release#25]
During the bintrayUpload, it fails on javaDoc generation. It cannot find my `com.library.R` and `BuildConfig`. Is there a way to solve this ?

**Comment by blundell** [comment]
stacktrace?

**Comment by HugoGresse** [comment]
/Users/hugogresse/Documents/Dev/../Constants.java:9: error: cannot find symbol
        public static final String SDK_VERSION = BuildConfig.VERSION_NAME;
                                                 ^
      symbol:   variable BuildConfig
      location: class Constants


I'm searching for writing my own AndroidArtifacts to have : 
    task androidJavadocs(type: Javadoc) {
        // add this line
        failOnError false
        source = android.sourceSets.main.allJava
    }

but not sure a achieve this.

**Comment by blundell** [comment]
hmm so your project is multi module? could you give some more details on the project setup and/or recreation steps

**Comment by HugoGresse** [comment]
It's an Android library using 3 jar lib (exoplayer builded by me, common-io and renderscriptv8). The android library in an SDK. It's probably not related to your plugins. The project contains some configuration but it's all prety basics. 

Are you sure there is no way to add failOnError ? Or exclude javadoc for release ?

**Comment by xrigau** [comment]
@HugoGresse I think as a temporary fix it might be possible to use your own Artifacts class. I've written something here (I haven't been able to test it so I'm not 100% sure it works) https://github.com/novoda/bintray-release/issues/24#issuecomment-90613024

**Comment by ouchadam** [comment]
the root problem has been fixed in `0.2.10` (library classpath missing from the javadoc classpath), if you feel that a `failOnError` would still be beneficial please open a new issue :+1: 

as for excluding, there's always the possibility of excluding the task *as of 0.2.10* `-x mavenAndroidJavaDoc`
