### ISSUE TITLE
org.apache.http.conn.HttpHostConnectException: Connection to https://api.bintray.com refused

### ISSUE THREAD

**Issue by KunMinX** [novoda/bintray-release#252]
From October 20th to now, the problem has been going on for nearly 1 months. Even using VPN is also helpless.

**Comment by KunMinX** [comment]
in project build.gradle

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.novoda:bintray-release:0.8.1'
    }

in library build.gradle

apply plugin: 'com.android.library'
apply plugin: 'maven'
apply plugin: 'com.novoda.bintray-release'

...

publish {
    userOrg = 'viabus-architecture'
    groupId = 'com.kunminx.viabus'
    artifactId = 'viabus-core'
    publishVersion = build_versions.versionName
    desc = 'viabus architecture for android'
    licences = ['Apache-2.0']
}

**Comment by KunMinX** [comment]
thanks god, it works, after trying 5 times today... after 20 days

**Comment by KingJA** [comment]
I have the same trouble, could anyone help? What happened with bintray?

**Comment by mr-archano** [comment]
@KingJA @KunMinX I'm sorry to hear you are facing some problems, but the issues in this repo are used to discuss bugs and feature requests related to the gradle plugin, while what you report is a problem with Bintray directly, related to network setup or other type of issues.

Feel free to reach out to them directly or ask on stackoverflow if you need more help that is not related to this plugin.
