### ISSUE TITLE
use version 0.9 ，it publishing failed

### ISSUE THREAD

**Issue by SpringSmell** [novoda/bintray-release#253]
unable to access https://api.bintray.com

> Task :quick-component:bintrayUpload 
Uploading to https://api.bintray.com/content/quick/maven/quick-component/0.0.7/org/quick/android/quick-component/0.0.7/quick-component-0.0.7-sources.jar...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':quick-component:bintrayUpload'.
> javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':bintrayPublish'.
> java.net.SocketTimeoutException: Read timed out

**Comment by mr-archano** [comment]
@SpringSmell It looks like a network error while trying to contact Bintray, sorry but there's not much we can do in this regard. Check your connection and your proxy settings and try again.

We have received few mentions about similar errors, it seems like from time to time Bintray is not reachable. I would consider to contact Bintray directly.
