### ISSUE TITLE
Typos of tasks' name

### ISSUE THREAD

**Issue by berberman** [novoda/bintray-release#254]
Please see 
https://github.com/novoda/bintray-release/blob/7828a1b2eb21385d6a07f0db123d9a16a985f677/plugin/core/src/main/groovy/com/novoda/gradle/release/MavenPublicationAttachments.groovy#L30

and

https://github.com/novoda/bintray-release/blob/7828a1b2eb21385d6a07f0db123d9a16a985f677/plugin/core/src/main/groovy/com/novoda/gradle/release/MavenPublicationAttachments.groovy#L37

Is `genereate` a synonym for `generate` or just a typo? 💯

**Comment by StefMa** [comment]
Well, good catch.
Its just a typo. Feel free to send a PR ☺

**Comment by mr-archano** [comment]
Thanks for the heads-up @berberman: it is a typo indeed and copy/pasting didn't help 😅 
I am going to open a PR shortly, it will be fixed in next release 👍

**Comment by mr-archano** [comment]
Fixed in [`0.9.1`](https://github.com/novoda/bintray-release/releases/tag/0.9.1)
