### ISSUE TITLE
Android prompt can not find Activity, Application, Context?

### ISSUE THREAD

**Issue by RockyQu** [novoda/bintray-release#257]
> Task :Common:javadocRelease 
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\component\AppComponent.java:3: 错误: 程序包android.app不存在
import android.app.Activity;
                  ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\component\AppComponent.java:4: 错误: 程序包android.app不存在
import android.app.Application;
                  ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\component\AppComponent.java:6: 错误: 程序包android.content不存在
import android.content.Context;
                      ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\component\AppComponent.java:43: 错误: 找不到符号
    Application getApplication();
    ^
  符号:   类 Application
  位置: 接口 AppComponent
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\integration\IRepositoryManager.java:3: 错误: 程序包android.content不存在
import android.content.Context;
                      ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\module\AppModule.java:3: 错误: 程序包android.app不存在
import android.app.Application;
                  ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\di\module\AppModule.java:4: 错误: 程序包android.content不存在
import android.content.Context;
                      ^
D:\Android\Workspace\MVPFrames\Common\src\main\java\me\mvp\frame\widget\imageloader\ImageLoader.java:3: 错误: 程序包android.content不存在
import android.content.Context;

.
.
.
.
.

javadoc: 错误 - java.lang.NullPointerException
1 个错误
100 个警告

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Common:javadocRelease'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'D:\Android\Workspace\MVPFrames\Common\build\tmp\javadocRelease\javadoc.options'

**Comment by RockyQu** [comment]
use classpath 'com.novoda:bintray-release:0.9'

**Comment by zrq1060** [comment]
I have the same question

**Comment by RockyQu** [comment]
Previously using the 0.8.1 version is a successful upload

**Comment by romantiskt** [comment]
I have the same question,I have the same question?

**Comment by huhuang03** [comment]
> Previously using the 0.8.1 version is a successful upload

Hello, I have the same issue, and I will try 0.8.1...

**Comment by erehmi** [comment]
use `classpath 'com.android.tools.build:gradle:3.3.1'`

**Comment by jingyc0305** [comment]
> use `classpath 'com.android.tools.build:gradle:3.3.1'`

thank you very much
