### ISSUE TITLE
Failed to publish publication 'release' to repository 'mavenLocal'

### ISSUE THREAD

**Issue by yitianbu** [novoda/bintray-release#259]
* What went wrong:
Execution failed for task ':mylibrary:publishReleasePublicationToMavenLocal'.
> Failed to publish publication 'release' to repository 'mavenLocal'
   > Failed to install artifact com.wf.android:mylibrary:aar:1.0.0: /Users/anhuishengchaohushibazhenxinyongshechenxiaoqian/Tools/mvn-lib/com/wf/android/mylibrary/1.0.0/mylibrary-1.0.0.aar (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

publish {
    userOrg = 'wfzjsxqq'
    groupId = 'com.wf.android'
    artifactId = 'mylibrary'
    publishVersion = '1.0.0'
    desc = 'Oh hi, this is a nice description for a project, right?'
    bintrayUser = 'wfzjsxqq'
    bintrayKey = '1212212112212121212159'
}

I don not know how to solve this problem

**Comment by StefMa** [comment]
Which tasks do you run?
Try to call 'build' or at least 'assembleRelease' before calling the
bintrayPublish task...

**Comment by yitianbu** [comment]
I run this   ./gradlew :mylibrary:clean :mylibrary:build :mylibrary:bintrayUpload -PbintrayUser=yiitanbu -PbintrayKey=b88e2e22fcf2ef7a27d5f2f6

**Comment by neonwarge04** [comment]
I also encountered this problem:

> Could not determine the dependencies of task ':lib:publishReleasePublicationToMavenLocal'.
> > java.lang.UnsupportedOperationException (no error message)

Not sure if we documented this problem?

**Comment by ludovicroland** [comment]
@yitianbu and @neonwarge04 : which version of the project do you use ?

On my Android projects that use the version 0.9, I have the same issue after the update of the android gradle plugin and gradle to the latest version.

Updating the project on the version 0.9.1 of the project fixed the issue on my side :

```
classpath "com.novoda:bintray-release:0.9.1"
```

**Comment by HpBoss** [comment]
But I can't update to 0.9.1，only 0.9.0
