### ISSUE TITLE
Failed to send a message: Package should include sources as part of the package.

### ISSUE THREAD

**Issue by devShdKhan** [novoda/bintray-release#261]
I have update my aar and pom file successfully but when i am going to click on Add to Jcenter it is showing me below message.

'Failed to send a message: Package should include sources as part of the package.'

**Comment by mr-archano** [comment]
Sorry @devShdKhan but I fail to see how what you posted above is related to the Gradle plugin. Please provide more information about how to reproduce the issue, if any, with the plugin itself, not Bintray or Jcenter.
