### ISSUE TITLE
Minimum supported Gradle version is 4.10.1

### ISSUE THREAD

**Issue by rishabh876** [novoda/bintray-release#264]
This is my first time setting up Bintray.

I tried the following command
`gradle clean build bintrayUpload -PbintrayUser={USERNAME} -PbintrayKey={API_KEY} -PdryRun=false`

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/rishabhharit/Documents/GitHub/RoundedImageView/example/build.gradle' line: 1
> 
> * What went wrong:
> A problem occurred evaluating project ':example'.
> Failed to apply plugin [id 'com.android.application']
> Minimum supported Gradle version is 4.10.1. Current version is 4.9. If using the gradle wrapper, try editing the distributionUrl in /Users/rishabhharit/Documents/GitHub/RoundedImageView/gradle/wrapper/gradle-wrapper.properties to gradle-4.10.1-all.zip

I already have gradle-4.10.1-all.zip in my gradle-wrapper.properties. 
Android Studio version 3.3.1

**Comment by tasomaniac** [comment]
You are running global Gradle installation. You should start with `./gradlew`

Closing the issue since the error is coming from Android Gradle Plugin, not from this plugin. 

Let us know if it is not working and we can reopen. 

Thanks.
