### ISSUE TITLE
> Task :app:bintrayUpload Repository name, package name or version name are null for project: project ':app'

### ISSUE THREAD

**Issue by Testing-007** [novoda/bintray-release#269]
When applying this command in terminal

./gradlew clean build bintrayUpload -PbintrayUser= -PbintrayKey -PdryRun=false
then it will give the following message but still Build is Successful.

screenshot
Repo is not displaying add to the jCenter button in Bintray
What the solution to this problem?

**Comment by mr-archano** [comment]
@Testing-007 the description above is a bit confusing, especially the following part:
> screenshot
> Repo is not displaying add to the jCenter button in Bintray
> What the solution to this problem?

Could you please try to explain what's going on in more details?


If you are referring to the error message in the title:
```
Task :app:bintrayUpload Repository name, package name or version name are null for project: project ':app'
```
then the error seems pretty self explanatory: your publishing configuration is missing some mandatory fields. You could take a look at the README and the samples in the repo as reference to understand what's wrong in your case.

**Comment by iartem** [comment]
For the ones who encounter this: update your Gradle to 5.1+ and everything else to the most recent versions. Did the job for me.
