### ISSUE TITLE
How can i remove sources.jar and javadoc.jar of bintrayUpload process

### ISSUE THREAD

**Issue by wangduanqing5945** [novoda/bintray-release#270]
`> Task :recordsdk:bintrayUpload
Uploading to https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0-sources.jar...
Uploaded to 'https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0-sources.jar'.
Uploading to https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0-javadoc.jar...
Uploaded to 'https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0-javadoc.jar'.
Uploading to https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0.aar...
Uploaded to 'https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0.aar'.
Uploading to https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0.pom...
Uploaded to 'https://api.bintray.com/content/wangduanqing/MomoVideoSDK/record/1.0.0/com/immomo/media/record/1.0.0/record-1.0.0.pom'.
`

I don't want to show my source and my doc. How can i do ?

**Comment by mr-archano** [comment]
@wangduanqing5945 I am not sure this is actually possible at the moment.
Could you try to just disable the relevant tasks from the command line using `-x $taskName`? (where `$taskName` is the name of the task creating a jar from sources/javadoc, as created [here](https://github.com/novoda/bintray-release/blob/master/plugin/core/src/main/groovy/com/novoda/gradle/release/MavenPublicationAttachments.groovy#L30) and [here](https://github.com/novoda/bintray-release/blob/master/plugin/core/src/main/groovy/com/novoda/gradle/release/MavenPublicationAttachments.groovy#L37)).

**Comment by chia7712** [comment]
@mr-archano I followed your suggestion to add `-x generateJavadocsJarForMavenPublication` and the following exception ensues.
```
Execution failed for task ':ohara-agent:publishMavenPublicationToMavenLocal'.
> Failed to publish publication 'maven' to repository 'mavenLocal'
   > Invalid publication 'maven': artifact file does not exist: '/xxxx-javadoc.jar'

```

**Comment by marandaneto** [comment]
@wangduanqing5945 I think it might be possible if you define your own publication and its artifacts, eg https://github.com/novoda/bintray-release/wiki/Defining-a-custom-Publication

**Comment by stfnt** [comment]
fix https://github.com/novoda/bintray-release/pull/331
