### ISSUE TITLE
bintrayUpload task graph misses publishMavenPublicationToMavenLocal 

### ISSUE THREAD

**Issue by motorro** [novoda/bintray-release#271]
**Observation**:
Plugin does not perform `publishMavenPublicationToMavenLocal` on Windows machine (presumably) while Linux works fine.
Gradle version: gradle-5.2.1-all (wrapper)
**Test command**:
```bash
./gradlew -m clean bintrayUpload -PbintrayUser=xxx -PbintrayKey=xxx -PdryRun=true --no-daemon
```
**Windows machine result**:
```bash
:clean SKIPPED
:base:clean SKIPPED
:base:compileKotlin SKIPPED
:base:compileJava SKIPPED
:base:processResources SKIPPED
:base:classes SKIPPED
:base:inspectClassesForKotlinIC SKIPPED
:base:jar SKIPPED
:base:sourcesJar SKIPPED
:base:assemble SKIPPED
:base:bintrayUpload SKIPPED
```
**Linux machine result**:
```bash
:clean SKIPPED
:base:clean SKIPPED
:base:compileKotlin SKIPPED
:base:compileJava SKIPPED
:base:processResources SKIPPED
:base:classes SKIPPED
:base:inspectClassesForKotlinIC SKIPPED
:base:jar SKIPPED
:base:sourcesJar SKIPPED
:base:assemble SKIPPED
:base:generatePomFileForMavenPublication SKIPPED 
:base:javadoc SKIPPED
:base:genereateJavadocsJarForMavenPublication SKIPPED
:base:genereateSourcesJarForMavenPublication SKIPPED
:base:publishMavenPublicationToMavenLocal SKIPPED
:base:bintrayUpload SKIPPED
```

References: #262

**Comment by motorro** [comment]
@mr-archano I've managed to:
1) Make tests to run on windows
2) Add dummy pure-Kotlin and Kotlin-Android tests to project
However the original issue is not reproduced by current test setup.
May be it is because of some other plugin in my original setup.
Will try to move 'em to test fixture one-by-one to try to reproduce

**Comment by jixiang52002** [comment]
i meet the same issue,does it deal?

**Comment by st235** [comment]
the same issue :-(

**Comment by mr-archano** [comment]
@motorro is this issue still relevant?

**Comment by motorro** [comment]
> @motorro is this issue still relevant?

Yes. But I don't care much :)
Yo may take a look at the config here:
- [AppUpdateWrapper](/motorro/AppUpdateWrapper)
- [RxLceModel](https://github.com/motorro/RxLceModel)

Both use the 0.9.1 but the first is a Java library while the second is an Android one

**Comment by mr-archano** [comment]
Thanks for the reply @motorro, I am trying to tidy up the current list of issues and I was wondering whether we should keep this open or not.
Just took a quick look at your setup, is this the way to workaround the issue you had? https://github.com/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/build.gradle#L90-L107

**Comment by motorro** [comment]
@mr-archano,
Those lines are the workaround for my CI builds on Travis for issue #262 as described [here](https://github.com/novoda/bintray-release/issues/262#issuecomment-471919006).
The problem there was overwriting sources jar with the empty one.
So here is my CI '[patch](https://github.com/motorro/AppUpdateWrapper/blob/master/.travis.yml#L53)':
```
./gradlew assemble generatePomFileForReleasePublication -x publishToMavenLocal bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false --no-daemon
```
Again, this issue is just a separation of graph generation issue from #262
