### ISSUE TITLE
Gradle 4.10

### ISSUE THREAD

**Issue by UttamPanchasara** [novoda/bintray-release#273]
Please release the latest version with latest Gradle 4.10 version support,

Not able to build the project when I have updated the Project Gradle version 4.3 to 4.10 latest.

Getting Following Error :

```
Unable to load class 'com.android.builder.errors.EvalIssueReporter'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

```

Latest available versions : https://developer.android.com/studio/releases/gradle-plugin

```
build.gradle:
classpath 'com.android.tools.build:gradle:3.3.2'

gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

```

Thanks

**Comment by mr-archano** [comment]
@UttamPanchasara it seems like there's some confusion here: the plugin in its actual form supports Gradle 4.10

What you posted seems related to the *Android Gradle Plugin*, perhaps a more recent version than the one we test against at the moment (see https://github.com/novoda/bintray-release/blob/master/plugin/core/src/test/groovy/com/novoda/gradle/release/ReleasePluginTest.groovy#L48).

We will take a look, but if you are in need of a fix you're welcome to take a stab at it and issue a PR.

**Comment by UttamPanchasara** [comment]
Agree, but I think the wrapper file still have an older version of Gradle and because of that In android it cause the problem in building project with latest Gradle version.

Current **gradle-wrapper.properties:**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-all.zip

//I think it should be like as below:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

```

**Comment by tasomaniac** [comment]
The wrapper used in this project is used to compile this one. It is up to you to use a newer one in your project. Afaik, it is currently compatible with 4.10.

It seems like you have another problem in your project.

**Comment by UttamPanchasara** [comment]
True, there was some problem with the project, I don't know what was the problem.

I performed the following steps:
Delete .idea folder
Delete .gradle folder
Clear cache
Restart studio - system

And now it's working, but getting a warning which was not there before: [Issue-260](https://github.com/novoda/bintray-release/issues/260)

Thanks for the support.
