### ISSUE TITLE
specify package name

### ISSUE THREAD

**Issue by moagrius** [novoda/bintray-release#275]
My bintray/jcenter package name is my FQDN, e.g., `com.my.project`.  So when I'm on bintray I see `myusername/maven/com.my.project`.  I've previously been manually uploading these files from an older script that generated sources only.  This plugin creates a new package name equal to my artifactId, so i end up with files at `myusername/maven/project` instead.  The DSL does look like it supports a package name (pkg.name) but this doesn't appear to be supported a Publish option.

The gradle implementation is the same either way `implementation 'com.my:project:1.2.3'`

Since this new project was not yet approved for including in jcenter, but my old project was (it's been around for many years), I tried merging the projects, which was probably a mistake, but the option of just moving to this new package name is no longer an option.

Is there a way I get this uploaded to that specific package name, without altering the groupId or artifactId?

TYIA

**Comment by mr-archano** [comment]
@moagrius if I understand correctly your problem you should be able to use `uploadName` to achieve that, see https://github.com/novoda/bintray-release/blob/master/plugin/core/src/main/groovy/com/novoda/gradle/release/BintrayConfiguration.groovy#L31

Could you please try and let us know?

**Comment by moagrius** [comment]
Thanks for the reply.  I'll try this as soon as I can this weekend and let you know.

**Comment by mr-archano** [comment]
Great, thanks @moagrius. You could also take a look at the wiki page linked in the README for more information on the publish configuration: https://github.com/novoda/bintray-release/wiki/Configuration-of-the-publish-closure

**Comment by moagrius** [comment]
this ended up becoming moot for reasons on my end, but i believe you're correct and that `uploadName` would do exactly that.  thanks for the fast response.  closing
