### ISSUE TITLE
Need to make repo and package before

### ISSUE THREAD

**Issue by ManojBehera** [novoda/bintray-release#277]
Hi,

Do we need to make repo and package in bintray before executing below command??

./gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false

Or this will automatically create repo and package and upload??

**Comment by StefMa** [comment]
You have to create the Repo manually in bintray. The package will be
created by this plugin

**Comment by ManojBehera** [comment]
Thanks for response!
So are we providing repo name with below details ?
publish {
    userOrg = 'novoda'
    groupId = 'com.novoda'
    artifactId = 'bintray-release'
    publishVersion = '0.6.1'
    desc = 'Oh hi, this is a nice description for a project, right?'
    website = 'https://github.com/novoda/bintray-release'
}

**Comment by ManojBehera** [comment]
classpath 'com.novoda:bintray-release:<latest-version>'

this should be include in project level gradle file..

apply plugin: 'com.novoda.bintray-release' this will be used in library gradle file ??

**Comment by mr-archano** [comment]
@ManojBehera please take a look at the wiki (as mentioned in the README): https://github.com/novoda/bintray-release/wiki/Configuration-of-the-publish-closure
