### ISSUE TITLE
Novoda bintray-release do not support gradle 4.6 and higher

### ISSUE THREAD

**Issue by KunMinX** [novoda/bintray-release#286]
Present is 2019, in the last year, so many people have feedback this situation, but one year later, this problem is still exist.
Android need to use AndroidX which dependence on gradle 4.6 and higher, so I suggest that novoda support the new method as quickly as AndroidX is popular.

WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

**Comment by mr-archano** [comment]
@KunMinX what you see is just a warning and we are fully aware of the issue, and we encourage contributions.
There's an attempt of solving this issue via this PR https://github.com/novoda/bintray-release/pull/272
Feel free to check the conversation over there to understand what's the issue we are facing.

**Comment by KunMinX** [comment]
@mr-archano Thank you for your reply. And after tryning classpath 'com.novoda:bintray-release:0.9' instead of 0.9.1 or 0.8.1, it works.

**Comment by mr-archano** [comment]
@KunMinX we had a temporary hiccup with syncing the package upstream to JCenter, so you might have experienced that `0.9.1` was not available to you. If you try to use `0.9.1.` again it should be fine now.
