### ISSUE TITLE
bintrayUpload is too slow and failed

### ISSUE THREAD

**Issue by KunMinX** [novoda/bintray-release#287]
I do not know what's going on, and it hardly to upload to bintray.

![](https://i.loli.net/2019/04/29/5cc6dd95e174c.png)

I'm in China and I can use VPN to visit Google for Android Developing. But it does not work for bintrayUpload.

So, what happened? If I choose to upload "source.jar, javadoc.jar, pom, aar" these four files by my self in bintray website, what's the local path of these 4 files so I can find them?

**Comment by StefMa** [comment]
They are in your local maven.
Checkout this site for further explanation:
https://www.baeldung.com/maven-local-repository

**Comment by KunMinX** [comment]
@StefMa  Thanks a lot, I found !

**Comment by BittleDragon** [comment]
@KunMinX 怎么解决的？求告知

**Comment by scarlee** [comment]
+1,fuck the wall

**Comment by KunMinX** [comment]
@BittleDragon @scarlee 
可到官网手动添加上传。上传的 4 个内容（source.jar, javadoc.jar, pom, aar）可在本地的 /user/.m2 目录中找到
