### ISSUE TITLE
Support for labels

### ISSUE THREAD

**Issue by johnjohndoe** [novoda/bintray-release#289]
The `gradle-bintray-plugin` defines `labels` in [their `pkg` configuration block](https://github.com/bintray/gradle-bintray-plugin#buildgradle).
Is this property supported by `bintray-release` or are you planning to add support?

**Comment by mr-archano** [comment]
It doesn't look like our plugin is supporting that property, but it should be fairly trivial to add. Want to contribute the change needed?

**Comment by johnjohndoe** [comment]
> Want to contribute the change needed?

I decided to use the [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin) instead. I won't work on the feature in the near future.
