### ISSUE TITLE
a bintray-release warning

### ISSUE THREAD

**Issue by strugglelin** [novoda/bintray-release#290]
apply plugin: 'com.novoda.bintray-release'
classpath 'com.novoda:bintray-release:0.9.1'

WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: CircleViewLibrary

**Comment by mr-archano** [comment]
Duplicated of https://github.com/novoda/bintray-release/issues/260
