### ISSUE TITLE
Cannot convert config to Gradle Kotlin DSL

### ISSUE THREAD

**Issue by erikhuizinga** [novoda/bintray-release#291]
My Android library is being converted from Groovy to the Kotlin DSL. However, converting this plugin's configuration script to Kotlin leads to Gradle errors.

The log can be found here: https://github.com/erikhuizinga/flomo/pull/2

I'm not sure if I'm doing something wrong, or if this plugin has an issue.

**Comment by mattmook** [comment]
Looking at the code this looks to be related to how Kotlin DSL works.

I have Kotlin DSL working in a few of my own projects, for example, https://github.com/appmattus/kotlinfixture/blob/master/bintray.gradle.kts
