### ISSUE TITLE
Could not find com.novoda:bintray-release:0.8.0.

### ISSUE THREAD

**Issue by kauramanp** [novoda/bintray-release#293]
I want to use Novada binary release in my project as an external library is using this but I'm getting errors

Could not find com.novoda:bintray-release:0.8.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.pom
  - https://dl.google.com/dl/android/maven2/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.jar
  - https://repo.maven.apache.org/maven2/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.pom
  - https://repo.maven.apache.org/maven2/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.jar
  - https://maven.google.com/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.pom
  - https://maven.google.com/com/novoda/bintray-release/0.8.0/bintray-release-0.8.0.jar
Required by:
    project :

**Comment by StefMa** [comment]
This plugin is not available in the repositories you have defined.
Simply add jcenter to your repositories.

**Comment by kauramanp** [comment]
Can you tell me how to do this?

**Comment by StefMa** [comment]
Checkout the Readme of this project how to do this. Or the official gradle
docs https://docs.gradle.org/5.6.1/userguide/declaring_repositories.html
