### ISSUE TITLE
INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

### ISSUE THREAD

**Issue by 908657085** [novoda/bintray-release#295]
INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

    private static def androidArchivePath(LibraryVariant variant) {
        return variant.outputs[0].packageLibraryProvider
    }

**Comment by mr-archano** [comment]
Duplicate of #260. Please in future be a good GitHub citizen and check whether the same issue has been raised before filing a new one. Thanks :bowing_man:
