### ISSUE TITLE
No files in own library after update

### ISSUE THREAD

**Issue by AlexDundar** [novoda/bintray-release#297]
I have the own library with some classes, and I added it into the bintray like it said in tutorial, with command
`$ ./gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false`

Now I need to make the update of library. I changed my classes and this libe in `build.gradle` file:
```
publish {
   ...
    publishVersion = 'new version here'
    ...
}
```
After that I wrote the same command:
`$ ./gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false`
And saw the message `BUILD SUCCESSFUL`.

The library version was updated in Jfrog Bintray console successfully too. 
BUT when I try to add my library with new version (in gradle dependencies) I cannt use any classes from it. All updates of this library are without classes. What I`m doing wrong and how to fix this problem?

**Comment by mr-archano** [comment]
@AlexDundar it looks like something is misconfigured in your project. Take a look at the [samples](https://github.com/novoda/bintray-release/tree/master/samples) and try to narrow down what's missing.
