### ISSUE TITLE
 javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by NBXXF** [novoda/bintray-release#299]
if used dataBinding  will throw  javax/xml/bind/JAXBException
![image](https://user-images.githubusercontent.com/14288893/68266406-ffc76a80-0089-11ea-82ad-7e855eb7d642.png)

**Comment by mr-archano** [comment]
@NBXXF I am closing this issue because doesn't provide any context or any explanation of what's going wrong. As far as I can tell your compilation task fails - and this plugin has nothing to do with compilation.

Feel free to open a new issue with the correct information (including repro-steps).
