### ISSUE TITLE
allow novoda's plugin to auto gpg signing on bintray

### ISSUE THREAD

**Issue by marandaneto** [novoda/bintray-release#301]
bintray's plugin already enable us to do that, but novoda's plugin not yet, we basically can achieve that adding a single attribute called `sign`, I've have set the default as `false`, so no side-effects nor breaking changes.
`sign` being `true` will tell bintray to sign artifacts using your custom gpg keypair if you have set one or bintray's keypair if you have chosen to use theirs, this is an opt-in feature.

I've made a PR for that, but it's only to show how simply would be, no tests yet (by tests I mean unit-tests).
https://github.com/novoda/bintray-release/pull/300/files

I already have tested it and it works with this single change.

**Comment by bruno-garcia** [comment]
#300

**Comment by marandaneto** [comment]
would it be possible to have an update here? at least if you all aim to have it as a feature, thanks.

**Comment by mr-archano** [comment]
sorry @marandaneto I must have missed your PR, but I just took a look.

**Comment by mr-archano** [comment]
PR merged, new snapshot with this change is released: https://bintray.com/novoda-oss/snapshots/bintray-release/develop-38

**Comment by mr-archano** [comment]
I'm preparing the release for `0.9.2` in the meantime

**Comment by mr-archano** [comment]
The PR is ready to go, I am waiting for an admin to take care of it (I am not part of the Novoda GitHub org anymore, sorry). That should be enough to release `0.9.2` in Bintray for everyone to use.

**Comment by marandaneto** [comment]
@mr-archano sounds awesome, thanks a lot, looking forward to using it :)

**Comment by mr-archano** [comment]
@marandaneto you could start using the snapshot if you like https://github.com/novoda/bintray-release/blob/master/README.md#snapshots
In the meantime I will ensure we can get a release as soon as possible.

**Comment by mr-archano** [comment]
Released as part of `0.9.2`: https://bintray.com/novoda-oss/maven/bintray-release/0.9.2

**Comment by marandaneto** [comment]
@mr-archano you may have forgotten to create the GitHub release btw. Thanks again.

**Comment by mr-archano** [comment]
Thanks for the reminder @marandaneto. Release created: https://github.com/novoda/bintray-release/releases/tag/0.9.2
