### ISSUE TITLE
Support for mavenCentralSync 

### ISSUE THREAD

**Issue by marandaneto** [novoda/bintray-release#303]
Hello all,

It would be nice to support the mavenCentralSync block, so we will have a single and full plugin-proxy to publish on bintray/jcenter and mavenCentral.

The idea code-wise would be:

Having a `mavenCentralSync` variable with the default value=`false`.
`user` and `password` via parameters like `-PmavenCentralUserToken=token` and `-PmavenCentralPassw=passw` or in the Plugin DSL of course, but most of the people won't hardcode it anyway, I guess.

If this is something that you all aim as a feature, I might do a PR :)

Thanks.

**Comment by mr-archano** [comment]
Sounds like a good idea to me tbh, and I don't see how this new feature would break anything so :+1: on my side. Feel free to share a snippet of the DSL if you want to discuss how that would look like or just issue a PR and talk over code (just remember to add me as reviewer so I will get the right notification)

**Comment by marandaneto** [comment]
@mr-archano here we go https://github.com/novoda/bintray-release/pull/304
for some reason, I cannot add you as a reviewer.

**Comment by bruno-garcia** [comment]
#304 was merged. Can this be closed?

**Comment by marandaneto** [comment]
@bruno-garcia new version isn't released though.

**Comment by marandaneto** [comment]
it's available if using the snapshot repo `com.novoda:bintray-release:develop-39`
