### ISSUE TITLE
Build failed with an exception when upload xxx.aar

### ISSUE THREAD

**Issue by suyunSSY** [novoda/bintray-release#306]
Uploading xxx.aar failed.

The following is the error message.

What went wrong:
Execution failed for task ':zegoliveroom:bintrayUpload'.
> java.net.SocketException: Broken pipe (Write failed)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.

**Comment by mr-archano** [comment]
Closing the issue as the error message mentioned above clearly states that is a `SocketException` (network failure).
We already have an issue tracking the use of deprecation warnings (#260)
