### ISSUE TITLE
AGP 3.6.0 support

### ISSUE THREAD

**Issue by afollestad** [novoda/bintray-release#308]
```
> Could not create an instance of type com.novoda.release.internal.compat.gradle5_3.AndroidSoftwareComponentCompat_Gradle_5_3.
   > org/gradle/api/internal/java/usagecontext/LazyConfigurationUsageContext
```

**Comment by afollestad** [comment]
(slightly related to #298 but not identical)

**Comment by marandaneto** [comment]
@afollestad I think it's the same though, have you tried using Gradle 5.x?

**Comment by afollestad** [comment]
This is with Gradle 5.6.4

**Comment by marandaneto** [comment]
@afollestad I see, interesting, because I've tested it and it works, you can check #307 there's even a unit/build test using Gradle 3.6.4 and AGP 3.6.0

**Comment by afollestad** [comment]
Oh it's because I was using Gradle 6.x 🤦‍♂sorry, yeah, 5.6.4 works.
