### ISSUE TITLE
javadoc tasks failing for android-gradle-plugin >= 3.6.0

### ISSUE THREAD

**Issue by Ashok-Varma** [novoda/bintray-release#310]
javadocRelease/javadocDebug tasks failing for android-gradle-plugin > 3.6.0

Execution failed for task ':library:javadocRelease'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting):

it was not able to find any android related class
```
error: package android.view does not exist
import android.view.View;
```
 after 100 errors task fails

similar to #257

**Comment by i-show** [comment]
+1

**Comment by marandaneto** [comment]
+1

**Comment by demoNo** [comment]
+1
the same issue

**Comment by czy1991** [comment]
+1

**Comment by zhangkang19164** [comment]
+1

**Comment by hendraanggrian** [comment]
+1

Reverting back to android gradle plugin `3.5.4` fixes the issue.

**Comment by panpf** [comment]
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish
