### ISSUE TITLE
The attempt to release the Android library ends up being successful even if bintray user/key are wrong

### ISSUE THREAD

**Issue by agap** [novoda/bintray-release#314]
I started experimenting with this plugin today (version 0.9.2) and I could not release my library to bintray. At some point, I decided to replace the bintrayUser/bintrayKey with some made-up values just to see if the task will end with failure, but all I can see is 

```
> Task :library:bintrayUpload
Uploading to https://api.bintray.com/content/omitted/library-0.1-sources.jar...
Uploading to https://api.bintray.com/content/omitted/library-0.1-javadoc.jar...
Uploading to https://api.bintray.com/content/omitted/library-0.1.aar...
Uploading to https://api.bintray.com/content/omitted/library-0.1.pom...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL 
```

Which makes me wonder - is this plugin still functional?

**Comment by marandaneto** [comment]
you probably are running on `dryRun` mode

**Comment by agap** [comment]
@marandaneto I can't believe I've made such a stupid mistake, it looks like `dryRun` is on by default. 🤦 Thanks for pointing that out!
