### ISSUE TITLE
Cause: org/gradle/api/internal/java/usagecontext/LazyConfigurationUsageContext

### ISSUE THREAD

**Issue by firepmi** [novoda/bintray-release#318]
I got new issue on Android Studio 4.0

 `   
Cause: org/gradle/api/internal/java/usagecontext/LazyConfigurationUsageContext
`

Please let me know how I can fix this issue.

**Comment by StefMa** [comment]
You don't need this plugin for 4.0 anymore..

**Comment by wang-li** [comment]
@StefMa Can you indicate any alternative to this plugin?

**Comment by StefMa** [comment]
Sure. To create the publication use the build in support by the AGP: https://developer.android.com/studio/build/maven-publish-plugin

Then you can use the [bintray gradle plugin](https://github.com/bintray/gradle-bintray-plugin/) to publish the publication to bintray.

The latter is btw exactly what this plugin does.

**Comment by RUPALAVECINO** [comment]
This issue has been resolved in Capacitor version 2.1.2.

https://github.com/ionic-team/capacitor/issues/3003

Please update the Capacitor dependencies in package.json to version 2.1.2 and then in Android Studio click the button to sync the project with Gradle.

"@capacitor/android": "^2.1.2",
"@capacitor/core": "2.1.2",

**Comment by StefMa** [comment]
This is not an node plugin 😂

**Comment by marandaneto** [comment]
@StefMa this plugin is still useful if you want to ship sources and javadocs for Android projects,
which is required by Maven Central, as Bintray has the ability to auto-sync with Maven central, I still find it useful even using newer AGP versions.

**Comment by StefMa** [comment]
You can skip the sources and javadocs (and whatnot) without this task as well 🙃 .
But you're right. This will force you to setup all of this by yourself.
This plugin will take care of it; even if it still uses `internal` Gradle classes...

**Comment by marandaneto** [comment]
yep, for JVM projects is very easy already with:
```
java {
    withJavadocJar()
    withSourcesJar()
}
```

but still, AGP should offer something like:
```
android {
    withJavadocJar()
    withSourcesJar()
}
```
then this plugin will lose its meaning.

**Comment by JarvanMo** [comment]
facing the same issue.

**Comment by panpf** [comment]
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

**Comment by mccccccmike** [comment]
> I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

saved my life
