### ISSUE TITLE
Q: how can i configure to enable only particular publications to maven local?

### ISSUE THREAD

**Issue by 4ntoine** [novoda/bintray-release#319]
I have a library with few gradle flavours (per ABI) and we push it to bintray and it works:
```
flavorDimensions "abi"

  productFlavors {
    abi_arm {
      dimension = "abi"
      ndk {
        abiFilters "armeabi-v7a"
      }

      externalNativeBuild {
        ndkBuild {
          arguments "APP_ABI=armeabi-v7a"
        }
      }
    }

    abi_arm64 {
      dimension = "abi"
      ndk {
        abiFilters "arm64-v8a"
      }

      externalNativeBuild {
        ndkBuild {
          arguments "APP_ABI=arm64-v8a"
        }
      }
    }

    abi_x86 {
      dimension = "abi"
      ndk {
        abiFilters "x86"
      }

      externalNativeBuild {
        ndkBuild {
          arguments "APP_ABI=x86"
        }
      }
    }

    abi_x86_64 {
      dimension = "abi"
      ndk {
        abiFilters "x86_64"
      }

      externalNativeBuild {
        ndkBuild {
          arguments "APP_ABI=x86_64"
        }
      }
    }

    abi_all {
      dimension = "abi"
      ndk {
        abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
      }
    }
  }
...

publish {
    userOrg = rootProject.ext.bintrayUserOrg
    groupId = rootProject.ext.bintrayGroupId
    artifactId = 'adblock-android'
    publishVersion = rootProject.ext.moduleVersion
    licences = rootProject.ext.bintrayLicences
    website = rootProject.ext.bintrayWebsite
    issueTracker = rootProject.ext.bintrayIssueTracker
    repository = rootProject.ext.bintrayRepository
    publications = ['abi_allRelease']
  }
...
```

As you can see only 1 publication (`abi_allRelease`) is activated.

I need to push only `Abi_allRelease` to local maven repo (do the same as for remote repo).
Instead all the publications are pushed one-by-one overwriting the aar in the local maven repo:
```
publishAbi_allDebugPublicationToMavenLocal
publishAbi_allReleasePublicationToMavenLocal
publishAbi_arm64DebugPublicationToMavenLocal
publishAbi_arm64ReleasePublicationToMavenLocal
publishAbi_armDebugPublicationToMavenLocal
publishAbi_armReleasePublicationToMavenLocal
publishAbi_x86DebugPublicationToMavenLocal
publishAbi_x86ReleasePublicationToMavenLocal
publishAbi_x86_64DebugPublicationToMavenLocal
publishAbi_x86_64ReleasePublicationToMavenLocal
```

As a workaround i do disable few tasks as follows:
```
afterEvaluate {
  tasks.withType(PublishToMavenLocal) {
    it.enabled = it.name.contains("Abi_allRelease")
  }
}
```

What's the proper way to do it? Why remote configuration isn't applied to local maven repo?

**Comment by StefMa** [comment]
Which task do you run? 🤔

**Comment by 4ntoine** [comment]
`./gradlew publishToMavenLocal`

**Comment by StefMa** [comment]
This task is basically an aggregation of all available
'publishXYZToMavenLocal' tasks.

Whatever. If you only want to publish a specific publication use the
available 'publish[PublicationName]ToMavenLocal'.

You can run the 'tasks' task to see all available tasks.

**Comment by 4ntoine** [comment]
@StefMa As i wrote before i saw what tasks are available and even listed all of them. Probably i was not clear enough trying to explain why `./gradlew ./gradlew publishAbi_allReleasePublicationToMavenLocal` is inconvenient as it works only for 1 module from Gradle multimodule project. On other hand `./gradlew publishToMavenLocal` produces unpredictable artifact to be pushed to local maven repo as all the particular tasks overwrite the file.

**Comment by StefMa** [comment]
Ah okay. Understand. Your question is basically why the publication filter is not applied to the "mavenLocal" task but to the bintray publishing task.

Well, the reason is because the publishing to mavenLocal and the publishing to bintray are two separate gradle plugins. The are internal (hidden) in this novoda plugin.
The bintray plugin can be configured with the publication filter. And this is what the novoda plugin exposed.
The maven publish plugin hasn't such a filter by default.

So the right solution for you is:
Use the specific "publish[PublicationName]ToMavenLocal" task of you want to publish it to maven local.
This is the right and correct solution.

But maybe we could also form a feature request out of this. The novoda plugin authors should use the given publication filter to disable all the "mavenLocal" tasks like you do.

**Comment by 4ntoine** [comment]
@StefMa ok, thanks for the explanation. For now it seems my workaround works better for me than running multiple `./gradlew publish..ToMavenLocal` per each Gradle module.
