### ISSUE TITLE
POM project file is not valid 

### ISSUE THREAD

**Issue by abhi007tyagi** [novoda/bintray-release#320]
I am able to upload to Bintray. But when I link it to Jcenter I get error "POM project file is not valid"

**Comment by abhi007tyagi** [comment]
Able to link Jcenter

**Comment by StefMa** [comment]
Can you maybe explain what the issue was and how do you solved it?
Just for tracking maybe another people will jump into this issue too.

**Comment by abhi007tyagi** [comment]
I selected the MavenCentral tab and there was another link in mouseover window to add to Jcenter. I clicked that and it worked.
