### ISSUE TITLE
The new plugin bintray-publish supports Gradle 6.0+ and Android Gradle Plugin 4.0+

### ISSUE THREAD

**Issue by panpf** [novoda/bintray-release#326]
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

**Comment by StefMa** [comment]
Still issues open without this information? 😒

**Comment by panpf** [comment]
The problem is fixed, please rest assured

**Comment by aivenlau** [comment]
thanks @panpf
