### ISSUE TITLE
When can update  gradle support 6.0+

### ISSUE THREAD

**Issue by hegaojian** [novoda/bintray-release#329]

**Comment by panpf** [comment]
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

**Comment by hegaojian** [comment]
Thank you very much, let me try :smiley: @panpf

**Comment by miqt** [comment]
👍

**Comment by hegaojian** [comment]
点开各位老哥的信息一看，嗐，都是龙的传人，那我还说啥子鸟英语啊  :laughing:

**Comment by bio007** [comment]
+1

**Comment by adrianolc** [comment]
+1

**Comment by is1988** [comment]
> 点开各位老哥的信息一看，嗐，都是龙的传人，那我还说啥子鸟英语啊 😆

龙的传人可还行:+1::+1::+1:

**Comment by nEdAy** [comment]
+1

**Comment by gzzlit** [comment]
牛的
