### ISSUE TITLE
upload success but it was not working

### ISSUE THREAD

**Issue by jjhesk** [novoda/bintray-release#37]
i have done the bintray upload to repository and it was done. But however it is still working available for download as I use the full path

```gradle

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    //compile project(':library')
    compile 'com.hkm:hkmprocessbuttons:1.0.61:@aar'
}

```
did i do anything wrong?

```

Error:(20, 13) Failed to resolve: com.hkm:hkmprocessbuttons:1.0.61
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

```

i have check the library location in [HERE](https://bintray.com/jjhesk/maven/hkmprocessbuttons/1.0.61/view)

**Comment by jjhesk** [comment]
Do i need to sync into jcenter as it mentioned?


Error:A problem occurred configuring project ':sample'.
> Could not resolve all dependencies for configuration ':sample:_debugCompile'.
   > Could not find com.hkm:hkmprocessbuttons:1.0.61.
     Searched in the following locations:
         https://jcenter.bintray.com/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.pom
         https://jcenter.bintray.com/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.aar
         https://repo1.maven.org/maven2/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.pom
         https://repo1.maven.org/maven2/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.aar
         file:/Users/hesk/Library/Android/sdk/extras/android/m2repository/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.pom
         file:/Users/hesk/Library/Android/sdk/extras/android/m2repository/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.aar
         file:/Users/hesk/Library/Android/sdk/extras/google/m2repository/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.pom
         file:/Users/hesk/Library/Android/sdk/extras/google/m2repository/com/hkm/hkmprocessbuttons/1.0.61/hkmprocessbuttons-1.0.61.aar
     Required by:
         hkm-progress-button:sample:unspecified

**Comment by blundell** [comment]
you no longer need the @aar. It also checks a couple of hours for bintry (where you linked from) to sync with JCenter (where gradle downloads from). Have you checked again this morning?

**Comment by ouchadam** [comment]
to use the `jcenter()` yep you'll to to link it (there's a button on bintray to do it) otherwise you'll need to add the direct url

```groovy
repositories {
  maven {
    url 'https://dl.bintray.com/user/reponame  
  }
}
```

**Comment by jjhesk** [comment]
@ouchadam so like you have said, if i want to just use jcenter() i will need to wait for couple hours from the sync?

**Comment by xrigau** [comment]
@jjhesk you need to request addition of your library to jCenter (there's a button in the repo screen in bintray and you get a reply once it gets accepted)

**Comment by xrigau** [comment]
and yeah it might take up to half a day to get a reply to get accepted

**Comment by ouchadam** [comment]
once accepted, all future updates will sync automatically to jcenter

**Comment by ouchadam** [comment]
you may have encountered the version bug in `0.2.9` which caused the version to be `unspecified`, please try again with `0.2.10` and let us know if everything works!

**Comment by ouchadam** [comment]
seems like your link works fine from `jcenter`, just needed some time to sync
