### ISSUE TITLE
Description property not set due to naming clash

### ISSUE THREAD

**Issue by jenzz** [novoda/bintray-release#46]
Using the latest release **com.novoda:bintray-release:0.2.10** the description property is not being set.

It's most probably another naming clash like #43 since `description` is also an attribute of [org.gradle.api.Project](http://gradle.org/docs/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:description).
I suggest using `desc` instead to match the `project.bintray.pkg.desc` field.

**Comment by ouchadam** [comment]
makes sense, as for the namings maybe nows a good time to change all of them to something like "bintray.version" "bintray.description" to future proof? cc @devisnik

**Comment by devisnik** [comment]
Sounds good to me. I did some experimenting on that in the #45 branch. It uses the `publish` prefix though to match the plugin name. It's in the `PublishExtension` class.
