### ISSUE TITLE
Cannot specify BSD-3-Clause as license

### ISSUE THREAD

**Issue by emilsjolander** [novoda/bintray-release#55]
With the following setup i receive a 400 bad request when trying to upload my artifacts. Specifying an Apache license works fine using the same setup.

```groovy
publish {
    ...
    licences = ['BSD-3-Clause']
}
```

**Comment by blundell** [comment]
have you tried `licences = ["BSD-3-Clause"]` got a feeling it might be groovys string interpretatiosn

**Comment by emilsjolander** [comment]
Yes, same issue

**Comment by emilsjolander** [comment]
This is no longer an issue, the correct id for the license i want is `BSD 3-Clause` not `BSD-3-Clause` as stated in http://spdx.org/licenses/
