### ISSUE TITLE
Kotlin android library mavenAndroidJavadocs task fail

### ISSUE THREAD

**Issue by busylee999** [novoda/bintray-release#71]
I try to publish my android library on Kotlin using bintray-release plugin and feared followed error:

<code>
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/InfoEntry.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/ObjectInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/BooleanPreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/FloatPreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/IntPreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/LongPreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/PreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/info/preferences/StringPreferenceInfo.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/mutable/BooleanMutable.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/mutable/MutableEntry.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/mutable/SetStringMutableEntry.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/ui/DevPanelActivity.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/ui/InfoListAdapter.kt"
javadoc: error - Illegal package name: "/Users/busylee/work/DevPanel/devpanellib/src/main/kotlin/com/busylee/devpanel/ui/PanelLinearListView.kt"
14 errors
:devpanellib:mavenAndroidJavadocs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':devpanellib:mavenAndroidJavadocs'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/busylee/work/DevPanel/devpanellib/build/tmp/mavenAndroidJavadocs/javadoc.options'</code>

**Comment by kollway-app** [comment]
you can try add the followed code to ignore checking javadoc's error(add these code into build.gradle file):
allprojects {
    tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
    }
}

hope it helps you.

**Comment by busylee999** [comment]
It did not help. Any ideas?

**Comment by BennyWang** [comment]
I face the same problem, How can I skip the javadoc task for kotlin sources

**Comment by busylee999** [comment]
Have you tried to exclude explicit tasks?

**Comment by busylee999** [comment]
... -x mavenAndroidJavadocs ... helps me
you can read more about skipping tasks here http://www.practicalgradle.org/blog/2010/10/skipping-tasks/

**Comment by BennyWang** [comment]
thank you very much

**Comment by asarazan** [comment]
I'm not an expert in the gradle api, but I fixed this in my personal `.gradle` files like this:
```gradle
task javadoc(type: Javadoc) {
    excludes = ['**/*.kt'] // < ---- Exclude all kotlin files from javadoc file.
    // ...
}
```

**Comment by xrigau** [comment]
This is a problem in the Javadoc generation itself and not in this plugin, many suggestions in this thread work, for me adding this to the library `build.gradle` file worked well

```groovy
tasks.withType(Javadoc) {
    options.addBooleanOption('Xdoclint:none', true)
}
```

from: http://stackoverflow.com/questions/34874175/disable-all-javadoc-in-gradle

Thanks all for your input.

**Comment by ebnbin** [comment]
I don't think this is the best way but it works for me. Add

```gradle
tasks.withType(Javadoc).all {
    enabled = false
}
```

to your build.gradle.

Hope it helps.

**Comment by BoxResin** [comment]
@ebnbin It worked for me!

**Comment by AdamSHurwitz** [comment]
@busylee999 Unfortunately your link from December 25, 2015 above no longer works. http://www.practicalgradle.org/blog/2010/10/skipping-tasks/. 

Where did you insert **-x mavenAndroidJavadocs**. Was this in the app or project level gradle file?

**Comment by briansalvattore** [comment]
@ebnbin worked!! Ty

**Comment by hendraanggrian** [comment]
I'm just wondering here, is [dokka](https://github.com/Kotlin/dokka) in any way supposed to fix this issue?

**Comment by zcabez** [comment]
After doing @ebnbin solution, i clean & rebuild my project and it worked. Thank you!!

**Comment by erikhuizinga** [comment]
It seems this issue has become a place to discuss problems with Kotlin and `androidJavadocs`... 😹 

@hendraanggrian Yes, dokka can fix the problem if you disable `androidJavadocs` and let dokka create docs for all languages in you project (e.g. Java and Kotlin). It can also create Javadoc, if you want you documentation to look just like if you just have Java.

However, in my particular project I have problems with the generation of Javadocs, but nothing breaking; it just takes a long time to generate the docs compared to `androidJavadocs`: 3 minutes vs. 10 seconds.

So, can it replace `androidJavadocs`: yes. Does it replace it with flair and grace: no.

**Comment by nirukk52** [comment]
@asarazan

**Comment by nirukk52** [comment]
@asarazan   
Its giving me this Cannot add task ':<...>:javadoc' as a task with that name already exists.

**Comment by StefMa** [comment]
The thing is that dokka can't be displayed in IntelliJ somehow.
I don't know why but the issue is described [here](https://github.com/Kotlin/dokka/issues/215).
Meaning if you don't publish your sources and generate the javadoc via dokka, the consumer of your lib will not be see the javadoc in IntelliJ.

**Comment by chrislin89** [comment]
I have tried all solutions what explained above comments.
But I am getting error like below:

```
...
> Task :library-kt-beta:javadoc FAILED
javadoc: error - Illegal package name: "....\xxxManager.kt"
javadoc: error - Illegal package name: "....\xxxActivity.kt"
javadoc: error - Illegal package name: "....\xxxFragment.kt"
javadoc: error - Illegal package name: "....\xxxObject.kt"
...
7 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library-kt-beta:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '....\library-kt-beta\build\tmp\javadoc\javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
37 actionable tasks: 33 executed, 4 up-to-date
```
