### ISSUE TITLE
Cannot upload to bintray repository

### ISSUE THREAD

**Issue by kollway-app** [novoda/bintray-release#72]
I uploaded my library on bintray repository successful last week, but today it cannot upload, although the terminal prints "BUILD SUCCESSFUL", I could not found it on bintray, I haven't change any code, whats wrong it is?

**Comment by kollway-app** [comment]
I have try type "gradlew bintrayUpload --info" to trace the detail, and everything looks like normal, it has printed :
"(Dry run) Uploaded to 'https://api.bintray.com/content/kollway/AndroidLib/pull-to-refresh/1.0.1/com/kollway/androidlib/pull-to-refresh/1.0.1/pull-to-refresh-1.0.1.pom'."

But I copy the link above and open it at Browser, it shows "{"message":"Package '' was not found"}"

**Comment by blundell** [comment]
If you do a Dry Run - it does not upload anywhere, you need:

```
gradlew bintrayUpload  --info -PdryRun=false
```

See readme for the other paramaters you also need: https://github.com/novoda/bintray-release/blob/master/README.md

**Comment by xrigau** [comment]
yeah as @blundell says dry run is enabled by default
