### ISSUE TITLE
upload jar to jcenter in an android module

### ISSUE THREAD

**Issue by hongyangAndroid** [novoda/bintray-release#78]
I want upload a jar file to jcenter in an android module , the default upload is aar , what should I do?

**Comment by xrigau** [comment]
Have you tried following the steps in the README? https://github.com/novoda/bintray-release#adding-to-project

Are you trying to upload a jar from source code or a jar that's already generated?

**Comment by blundell** [comment]
no reply in over a year , closing

(fyi uploading an android library module is possible - follow the readme)
