### ISSUE TITLE
Upload two artifact from only one project

### ISSUE THREAD

**Issue by JcMinarro** [novoda/bintray-release#80]
I have a project with two modules, one of them is a gradle plugin and the other one is an Android Library. They both have to work together, because I have them on the same project. I have a `build.gradle` file on every module and into them I have integrated your plugin to upload to bintray. It seems to work, because I am able to upload both artifact to bintray, but I have a problem, it only upload a `.jar` file from my `gradle plugin` and a `.aar` file from my Android Library. But it doesn't upload any `.pom` file neither `sources` files. I am not sure if it is because your plugin doesn't work with two modules into one project or I am not configuring properly my `build.gradle` files.
You can see my project with your plugin integratino on the next branch:
https://github.com/JcMinarro/ProperDroid/tree/novodaPlugin

**Comment by kobakei** [comment]
I found same issue.
I have two modules (android library and apt processor) in one project. Then, android library was uploaded and published. However apt processor was uploaded but not published.

**Comment by blundell** [comment]
What is the behaviour you expect? 
Each module is uploaded and has to be used as a separate dependency, you can't upload two modules and expect it to somehow zip them together and create 1 dependency that isn't how it works. Is this your thinking?

**Comment by kobakei** [comment]
No. I expect two modules are uploaded to jcenter as two maven repos.
For example, my project with two modules have been uploaded to these repos.
https://bintray.com/kobakei/maven/spot/view
https://bintray.com/kobakei/maven/spot-compiler/view
But one module has not been published by the plugin.

**Comment by ouchadam** [comment]
This is possible, we've done something similar internally. 

Your modules need to be treated individually and your dependency version names shared

```
./gradlew module1:bintrayUpload
./gradlew module2:bintrayUpload
```

**Comment by JcMinarro** [comment]
@blundell I expect that after performing `gradle bintrayUpload...` have my two modules uploaded to bintray.

The result just now is that your plugin only uploads `.jar` and `.aar` files from my modules, but don't create neither upload any `.pom` related to those modules and then bintray doesn't allow them to be published.

I have my project with your plugin integration on [this branch](https://github.com/JcMinarro/ProperDroid/tree/novodaPlugin). You can see it and do some trails over it ;)

**Comment by yubaokang** [comment]
@kobakei
 you can upload one module,and then another.
but it can't use like
compile 'com.yubaokang:intentinject-api:v1.0.0'
apt 'com.yubaokang:intentinject-compiler:v1.0.0'
it must use like 
compile 'com.yubaokang:intentinject-api:v1.0.0'
compile 'com.yubaokang:intentinject-compiler:v1.0.0'
when i build apk ,the guava library will be builed in the apk.

**Comment by blundell** [comment]
tracking via: https://github.com/novoda/bintray-release/issues/16
