### ISSUE TITLE
Exception: mavenAndroidJavadocs

### ISSUE THREAD

**Issue by meNESS** [novoda/bintray-release#82]
Hi,

I'm getting following exception while publishing.

> 2 errors
> 1 warning
> :library:mavenAndroidJavadocs FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':library:mavenAndroidJavadocs'.
> > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'C:\Users\aessh\Documents\GitHub\TimelinePostContainer\library\build\tmp\mavenAndroidJavadocs\javadoc.options'

**Comment by xrigau** [comment]
yes this is a known issue, you can work around it by excluding the `mavenAndroidJavadocs` gradle task, just add `-x mavenAndroidJavadocs` to the gradle invocation

Example:

`gradle bintrayUpload -x mavenAndroidJavadocs`

**Comment by meNESS** [comment]
@xrigau That works fine. Thanks :+1:

**Comment by LingoGuo** [comment]
That works.Thanks a lot
