### ISSUE TITLE
Bintray upload success but not download via gradle and shows error like below 

### ISSUE THREAD

**Issue by ashishraval21** [novoda/bintray-release#83]
Error:A problem occurred configuring project ':app'.
> Could not find app.aar ("GRADLE depencency name ").
  Searched in the following locations:
      http://dl.bintray.com/songline/maven/"Gradle dependency name ". aar  file . 

Actually by mistake i was making same dependency name with bintray after delete that package  that i was making new package and dependency  with same name . but after deleting that it shows this is not found pls help me asap. :(

**Comment by xrigau** [comment]
Can you post the gradle output printed when uploading the library to bintray?

**Comment by ashishraval21** [comment]
@xrigau its solved already long time back , thanks for your response.

**Comment by xrigau** [comment]
Would be awesome if you could spend a minute writing how you solved it so that other people can refer to this in the future 😄
