### ISSUE TITLE
be success but not found file with pom?

### ISSUE THREAD

**Issue by go2av** [novoda/bintray-release#86]
android studio: `2.1`
gradle: `2.10`
mac: `10.10.5`
### not found file `pom`

![1321bcde-8e19-471c-aeba-452cec5f8554](https://cloud.githubusercontent.com/assets/10859832/15573819/2e18a76c-237c-11e6-9abc-b2f0771453dc.png)
### not found file `.jar` `.aar`

![fabf3982-c9c4-44d8-b00b-c2ccc2e45318](https://cloud.githubusercontent.com/assets/10859832/15573823/3deccb28-237c-11e6-8342-ff0d76afb588.png)

**Comment by chenhui3014** [comment]
+

**Comment by go2av** [comment]
@chenhui3014 😄  啊稀巴？

**Comment by chenhui3014** [comment]
generatePomFileForMavenPublication bintrayUpload
