### ISSUE TITLE
how to set javadoc encoding,My Code has Chinese note

### ISSUE THREAD

**Issue by LuckyJayce** [novoda/bintray-release#87]

**Comment by LuckyJayce** [comment]
i have solved it
append below code in gradle.
 
allprojects {
    tasks.withType(Javadoc) {
        options{
            encoding "UTF-8"
            charSet 'UTF-8'
            links "http://docs.oracle.com/javase/7/docs/api"
        }
    }
}

**Comment by xrigau** [comment]
Awesome, thanks for sharing @LuckyJayce ! 👍

**Comment by zhoushengming** [comment]
thanks! @LuckyJayce

**Comment by wannoo1990** [comment]
thanks! @LuckyJayce
