### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by qsxiaogang** [novoda/bintray-release#88]
What went wrong:
Execution failed for task ':common:bintrayUpload'.

> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

I got this error at last step. I have try to look about the error form google,but no solution.

Can you supply any suggestion ?

**Comment by iFarSeer** [comment]
+1

**Comment by wangzhiyuan** [comment]
+2

**Comment by ouchadam** [comment]
this seems quite odd 😿 , are you using a vpn? Is the bintray website certified for you?

<img width="213" alt="screen shot 2016-08-17 at 14 02 19" src="https://cloud.githubusercontent.com/assets/1848238/17737126/5556343c-6483-11e6-9f75-fd1046dd4b52.png">

**Comment by blundell** [comment]
no answer to the question posed in over a year - closing as can't reproduce
