### ISSUE TITLE
can not create javadoc.jar and sources.jar

### ISSUE THREAD

**Issue by yilylong** [novoda/bintray-release#90]
Skipping upload for missing file 'E:\MyAndroidSudioProgects\CBPullRefreshListView\CBPullRefresh\build\libs\CBPullRefresh-sources.jar'
Skipping upload for missing file 'E:\MyAndroidSudioProgects\CBPullRefreshListView\CBPullRefresh\build\libs\CBPullRefresh-javadoc.jar'.

**Comment by xrigau** [comment]
Did you check the files `E:\MyAndroidSudioProgects\CBPullRefreshListView\CBPullRefresh\build\libs\CBPullRefresh-sources.jar` `E:\MyAndroidSudioProgects\CBPullRefreshListView\CBPullRefresh\build\libs\CBPullRefresh-javadoc.jar` exist?

**Comment by chenhui3014** [comment]
How to solve this problem?

**Comment by amatkivskiy** [comment]
@xrigau @chenhui3014 @yilylong To fix this issue you need to add the following lines to your build.gradle
```
// custom tasks for creating source/javadoc jars
task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

// add javadoc/source jar tasks as artifacts
artifacts {
    archives sourcesJar, javadocJar
}
```

**Comment by kuyue** [comment]
you can execute the two tasks:
![image](https://user-images.githubusercontent.com/10491881/27531190-53364cd0-5a8e-11e7-95bc-afed7b001ba2.png)

**Comment by kkmike999** [comment]
add three more task `releaseAndroidJavadocs`,`releaseAndroidJavadocsJar`,`releaseAndroidSourcesJar `.

the total commend :
```
./gradlew clean build releaseAndroidJavadocs releaseAndroidJavadocsJar releaseAndroidSourcesJar generatePomFileForReleasePublication bintrayUpload -PbintrayUser=<bintray user> -PbintrayKey=<bintray api key> -PdryRun=false 
```

**Comment by sunxu3074** [comment]
I solved it by using [gradle-android-library](https://www.virag.si/2015/01/publishing-gradle-android-library-to-jcenter/)  , Hahahaha

**Comment by blueberryCoder** [comment]
I met this problem too.

I solve it by  delete this configs in gradle.properties

#org.gradle.daemon=false
#org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536m
#org.gradle.configureondemand=true

**Comment by skypfan** [comment]
//生成源文件
task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

//生成Javadoc文档
task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

//文档打包成jar
task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

//拷贝javadoc文件
task copyDoc(type: Copy) {
    from "${buildDir}/docs/"
    into "docs"
}

//上传到JCenter所需要的源码文件
artifacts {
    archives javadocJar
    archives sourcesJar
}

//添加下面这句
apply plugin: 'com.novoda.bintray-release'

publish {
    userOrg = '**'    //注册时候的用户名
    groupId = '***'//   //compile引用时的第1部分
    repoName = 'Maven'//要传到的maven的名字。你可能有多个maven，要传哪个写哪个
    artifactId = '****'////发布到JCenter上的项目名字，compile引用时的第2部分项目名
    publishVersion = '1.0.1'//版本号 ，compile引用时的最后部分，下次更新是只需要更改版本号即可
    desc = 'A customizable Lib on Android'//描述，不重要
    website = 'https://github.com/skypfan'  //项目的GitHub网站
}

// gradlew clean build generatePomFileForReleasePublication bintrayUpload -PbintrayUser=***-PbintrayKey=***-PdryRun=false

此配置可以解决sources.jar、javadoc.jar以及pom.xml文件缺失的问题
