### ISSUE TITLE
Compile time issue: non-zero exit value 1

### ISSUE THREAD

**Issue by amalChandran** [novoda/bintray-release#91]
Error:Execution failed for task ':rebound-android-example:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by xrigau** [comment]
hey @amalChandran this problem seems to be related with something else since it fails when running the `preDexDebug` gradle task so that happens way before any of the bintray code is run
