### ISSUE TITLE
Custom publications don't work

### ISSUE THREAD

**Issue by paveldudka** [novoda/bintray-release#93]
Gradle: 2.14.1

If custom publication is specified along with applying bintray-release plugin, build fails with following error:

```
Error:Cannot configure the 'publishing' extension after it has been accessed.
```

**Comment by xrigau** [comment]
hey @paveldudka thanks  for reporting, could you provide a piece of code to reproduce the issue? thanks!

**Comment by paveldudka** [comment]
Hey!
I created a sample project here https://github.com/paveldudka/BintrayPluginPlayground
Steps to repro are in readme.

I suspect this issue has something to do with the fact I also applied `maven-publish` plugin. But that's the only way I know to create a custom publication
