### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by dmitrikudrenko** [novoda/bintray-release#95]
I use the Kotlin and on uploading I receive error

```
java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0
```

**Comment by dmitrikudrenko** [comment]
I added 
```
compileOptions {
   sourceCompatibility JavaVersion.VERSION_1_7
   targetCompatibility JavaVersion.VERSION_1_7
}
```
but it didn't help

**Comment by WaiLynnZaw** [comment]
I have faced with same problem.
I tried to set Gradle version to 2.10 and Android Plugin Version to 2.1.2.
It worked for me!

**Comment by dmitrikudrenko** [comment]
Ok, I changed compileSdk to 23. Gradle to 2.10. Gradle plugin to 2.1.2. Also I added that task
```
subprojects {
    tasks.withType(Javadoc).all { enabled = false }
}
```
because there were fails in javadoc generation - "Invalid package name"

**Comment by weidongjian** [comment]
i have the same problem, I resolve by install java8, and restart computer

**Comment by ouchadam** [comment]
appears that this was an environment issue, feel free to reopen if the issue is still occurring!
