### ISSUE TITLE
Skipping upload for missing file pom-default

### ISSUE THREAD

**Issue by WaiLynnZaw** [novoda/bintray-release#96]
I tried as described in https://github.com/novoda/bintray-release/wiki/Add-support-for-syncing-to-maven-central and as in issue #19 

but still get Skipping upload for missing file pom-default.xml

I solved this issue by running -
./gradlew clean build generatePomFileForMavenPublication bintrayUpload -PbintrayUser=<BINTRAY_USER> -PbintrayKey=<BINTRAY_KEY> -PdryRun=false

**Comment by xrigau** [comment]
Thanks for the info @WaiLynnZaw 👍

**Comment by chenhui3014** [comment]
How to solve this problem ?

**Comment by yilylong** [comment]
i got "Task 'generatePomFileForMavenPublication' not found in root project  'xxx'   "

**Comment by kkmike999** [comment]
@yilylong 

try `generatePomFileForReleasePublication` or `publishReleasePublicationToMavenLocal`.

The full commend is:
```
./gradlew clean build generatePomFileForReleasePublicationbintrayUpload -PbintrayUser=<BINTRAY_USER> -PbintrayKey=<BINTRAY_KEY> -PdryRun=false
```

![](http://i4.piimg.com/577986/e1751f83bb3d80d2.png)

**Comment by HouXiaohu** [comment]
@yilylong how did you solve it ""Task 'generatePomFileForMavenPublication' not found in root project 'xxx' ""
