### ISSUE TITLE
one project two module 

### ISSUE THREAD

**Issue by yubaokang** [novoda/bintray-release#97]
- I have two modules (android library and apt processor) in one project. Then,they are be  published to jcenter.
  i must use like

``` java
compile 'com.yubaokang:intentinject-api:v1.0.0'
compile 'com.yubaokang:intentinject-compiler:v1.0.0'
```

it will add other library like guava library.
i want use them like 

``` java
compile 'com.yubaokang:intentinject-api:v1.0.0'
apt 'com.yubaokang:intentinject-compiler:v1.0.0'
```

but it not used!

here is how I publish them:
[IntentInject](https://github.com/yubaokang/IntentInject)

thanks!

**Comment by blundell** [comment]
tracking via https://github.com/novoda/bintray-release/issues/16
