### ISSUE TITLE
No Java runtime present, requesting install.

### ISSUE THREAD

**Issue by lisawray** [novoda/bintray-release#98]
Running this on a new computer and it's giving me this error.  

Is there some environment variable I need to set for this to succeed?  I have a Java runtime :)

$ which java
/usr/bin/java

**Comment by xrigau** [comment]
hey @lisawray what are you running to get that error? you shouldn't need the JAVA_HOME environment variable, but you'll need java in your PATH, did you check it's there?

**Comment by lisawray** [comment]
Sorry, I figured this out.  I had a new computer and it was pointing to a really old version of Java!

**Comment by xrigau** [comment]
Good to know, thanks!!
