### ISSUE TITLE
androidTest overwrites compile dependencies 

### ISSUE THREAD

**Issue by ouchadam** [novoda/bintray-release#99]
`androidTest` dependencies are being bundled into the release pom and also overwrite legit `compile` dependencies. 

```xml
    <dependency>
      <groupId>org.easytesting</groupId>
      <artifactId>fest-assert-core</artifactId>
      <version>2.0M10</version>
      <scope>runtime</scope>
    </dependency>
```

**Comment by StefMa** [comment]
Can't reproduce it.
Neither with androidTest **compile** nor with androidTest **implementation** or androidTest **api**.
![geist_1516980014985](https://user-images.githubusercontent.com/10229883/35446423-f49c526c-02b4-11e8-8a70-4e9c73f45daa.gif)
Seems to be already fixed.
If i run in that issue again feel free to open another issue 👍
